// Pure AssemblyGraph mutation entrypoints for the WS2 tool-call edit surface.
//
// Each exported mutator takes a graph + typed args, applies the change to a
// deep clone (never mutates the caller's copy), re-runs `validateTopology` on
// the result, and returns a structured pass/fail response. The response shape
// is the same one the backend marshals back to Claude as a `tool_result`:
//
// { ok: true, graph: <mutated>, warnings: string[] }
// { ok: false, code: <rule>, message: string, suggested_repair?: string }
//
// Staying pure (no THREE / DOM / presets.json I/O) is load-bearing: the
// fixture runner drives this from Node, and the Python edit-turn loop calls
// through the same API via urdfAssembly.ts. Every rule the TS validator
// knows about (sensor-on-actuator, shaft-fanout, port class mismatch,
// direct-servo-stack) is enforced here automatically — this module calls the
// same `validateTopology` that the placement engine runs.
//
// Port-mismatch enforcement: validateTopology doesn't check shaft/mount_face
// port classes (placement currently logs a warning and proceeds — the
// "detect→enforce gap" in `project_vector_improvement_plan.md` anti-patterns).
// This module closes that gap: `_checkPortCompatibility` rejects any mutation
// that would stack an actuator directly on another actuator's shaft face or
// land a shaft on a structural mount_face without a bracket in between.
// Auto-repair (Repair 5) fires for those cases in resolveAssemblyGraph, but
// per-call enforcement lets Claude fix it itself within the same turn instead
// of relying on a downstream repair that may not satisfy the user intent.

import { validateTopology, checkPortCompatibility, formatStructuredDiagnostic } from './topologyValidation.ts'
import type { ValidationContext, ValidationPreset } from './topologyValidation.ts'
import { cloneAssemblyGraph } from './urdfGraphEquivalence.ts'
import type { AssemblyComponent, AssemblyGraph } from './urdfGraphEquivalence.ts'

// Default 6-face connector ids generated by mateConnectors.generateDefault-
// Connectors. Inlined here (not imported from mateConnectors.ts) so this
// module stays THREE-free and keeps the toolDispatchCorpus runner cheap to
// boot under node --experimental-strip-types.
const DEFAULT_CONNECTOR_IDS: ReadonlySet<string> = new Set([
  'top', 'bottom', 'front', 'back', 'left', 'right',
])

// ── Tool-call argument types ────────────────────────────────────────────────

export interface AddLinkArgs {
  link_name: string
  parent_link: string
  component_id: string
  attach_face: string
  joint_type?: string
  joint_axis?: string
  length_mm?: number
  orientation?: string
  elevation_angle?: number
  attach_rpy?: number[]
  // Phase 4 — optional named-connector
  // overrides (see AssemblyComponent for semantics). Forwarded verbatim to
  // the new child component.
  attach_connector?: string
  mate_connector?: string
  mate_type?: string
}

export interface AttachSensorArgs {
  link_name: string
  parent_link: string
  component_id: string
  mount_face: string
  elevation_angle?: number
}

export interface ReplaceComponentArgs {
  link_name: string
  new_component_id: string
}

export interface SetJointArgs {
  link_name: string
  joint_type: string
  joint_axis?: string
  attach_rpy?: number[]
}

export interface RemoveLinkArgs {
  link_name: string
  reparent_children?: boolean
}

export type GraphMutation =
  | { kind: 'add_link';           args: AddLinkArgs }
  | { kind: 'attach_sensor';      args: AttachSensorArgs }
  | { kind: 'replace_component';  args: ReplaceComponentArgs }
  | { kind: 'set_joint';          args: SetJointArgs }
  | { kind: 'remove_link';        args: RemoveLinkArgs }

// ── Response shape ──────────────────────────────────────────────────────────

export interface MutationOk {
  ok: true
  graph: AssemblyGraph
  warnings: string[]
  /** Short human-readable summary (e.g. "added camera_1 on extrusion_1.top"). */
  summary: string
}

export interface MutationError {
  ok: false
  /** Stable rule code Claude can pattern-match on. */
  code: string
  message: string
  /** Short actionable hint (e.g. "attach to a structural extrusion instead"). */
  suggested_repair?: string
}

export type MutationResult = MutationOk | MutationError

// ── Port-compatibility (delegates to the shared validator helper) ───────────
// WS2: a port mismatch is a WARNING on both edit surfaces, not a reject — the
// same `checkPortCompatibility` powers the design_robot batch validator, so
// the two paths can never disagree about what's allowed. The warning carries
// the coupler-disc suggested_repair; Claude applies it or argues for the
// deliberate pairing.

function _portMismatchWarning(
  ctx: ValidationContext,
  parent: AssemblyComponent | undefined,
  child: AssemblyComponent,
): string | null {
  const diag = checkPortCompatibility(ctx, parent, child)
  return diag ? formatStructuredDiagnostic(diag) : null
}

// ── Connector-reference validation (CONNECTOR_MISS) ───────────────────────
// Catches the case the dev-throw at urdfAssembly.ts:2048 was intended to
// surface — an attach_connector or mate_connector that doesn't resolve on the
// targeted preset — BEFORE resolveAssemblyGraph runs. The dev-throw stays as
// defense-in-depth for genuine preset coverage holes; this layer turns AI
// hallucinations into structured tool errors / topology errors so the redesign
// loop can react instead of hard-crashing. See memory/project_engine_
// regression_connector_miss.md for the failure mode.

/** Set of connector ids resolvable on a preset: the 6 face defaults plus any
 *  authored connectors. Authored entries override defaults by id, but for an
 *  existence check that doesn't matter. */
function _connectorIdsFor(preset: ValidationPreset | null): Set<string> {
  const ids = new Set<string>(DEFAULT_CONNECTOR_IDS)
  if (!preset?.connectors) return ids
  for (const c of preset.connectors) if (c?.id) ids.add(c.id)
  return ids
}

/** Returns null when the component does not opt into named-connector semantics
 *  (legacy attach_face-only path), when the parent or child preset can't be
 *  found (UNKNOWN_COMPONENT / UNKNOWN_PARENT handle those upstream), or when
 *  every referenced id resolves. Otherwise returns a CONNECTOR_MISS detailing
 *  which side missed and the valid id set on that preset. */
function _checkConnectorReferences(
  ctx: ValidationContext,
  parent: AssemblyComponent | undefined,
  child: AssemblyComponent,
): MutationError | null {
  // Same opt-in gate as urdfAssembly.computeMatePlacement: only fire when the
  // component actually uses named-connector fields. Pure-attach_face graphs
  // ride the legacy bbox path and don't need this check.
  if (!child.attach_connector && !child.mate_connector && !child.mate_type) return null
  if (!parent) return null

  const parentPreset = ctx.findPreset(parent.component_id)
  const childPreset = ctx.findPreset(child.component_id)
  if (!parentPreset || !childPreset) return null

  const parentIds = _connectorIdsFor(parentPreset)
  const childIds = _connectorIdsFor(childPreset)

  // Mirror the resolver's id-derivation: parent uses attach_connector ?? attach_face ?? 'top';
  // child uses mate_connector ?? opposite-face(attach_face) ?? 'bottom'. Only the explicit
  // attach_connector / mate_connector values are AI-supplied — defaulted ids are always in the
  // set, so the only way to fail here is by naming a non-existent connector.
  const attachFace = child.attach_face ?? 'top'
  const parentConnectorId = child.attach_connector ?? attachFace
  const inferredChildId = child.attach_face
    ? (DEFAULT_CONNECTOR_IDS.has(child.attach_face)
        ? ({ top: 'bottom', bottom: 'top', front: 'back', back: 'front', left: 'right', right: 'left' } as Record<string, string>)[child.attach_face]
        : null)
    : null
  const childConnectorId = child.mate_connector ?? inferredChildId ?? 'bottom'

  const parentMiss = !parentIds.has(parentConnectorId)
  const childMiss = !childIds.has(childConnectorId)
  if (!parentMiss && !childMiss) return null

  const messages: string[] = []
  const repairs: string[] = []
  if (parentMiss) {
    const valid = [...parentIds].sort().join(', ')
    messages.push(`attach_connector="${parentConnectorId}" not on parent ${parent.component_id}`)
    repairs.push(`set attach_connector to one of [${valid}] (named connectors authored ON the parent), or move "${parentConnectorId}" to mate_connector if it lives on the child preset instead`)
  }
  if (childMiss) {
    const valid = [...childIds].sort().join(', ')
    messages.push(`mate_connector="${childConnectorId}" not on child ${child.component_id}`)
    repairs.push(`set mate_connector to one of [${valid}], or move "${childConnectorId}" to attach_connector if it lives on the parent preset`)
  }
  return {
    ok: false,
    code: 'CONNECTOR_MISS',
    message: `${child.link_name}: ${messages.join('; ')}.`,
    suggested_repair: repairs.join(' | '),
  }
}

/** Graph-wide pre-pass for resolveAssemblyGraph. Returns one CONNECTOR_MISS-
 *  prefixed error per offending component so the topologyErrors[] array carries
 *  the same content the dev-throw would have produced — but as a recoverable
 *  signal the redesign loop can act on. */
export function validateConnectorReferences(
  components: AssemblyComponent[],
  ctx: ValidationContext,
): string[] {
  const byName = new Map<string, AssemblyComponent>()
  for (const c of components) byName.set(c.link_name, c)
  const errors: string[] = []
  for (const c of components) {
    if (!c.attach_to) continue
    const parent = byName.get(c.attach_to)
    const err = _checkConnectorReferences(ctx, parent, c)
    if (err) errors.push(`[${err.code}] ${err.message} ${err.suggested_repair ?? ''}`.trim())
  }
  return errors
}

// ── Mutation dispatchers ────────────────────────────────────────────────────

function _validateAndRespond(
  graph: AssemblyGraph,
  ctx: ValidationContext,
  summary: string,
  extraWarnings: string[] = [],
): MutationResult {
  const { errors, warnings } = validateTopology(graph.components, ctx)
  if (errors.length > 0) {
    // Hard errors only (UNKNOWN_*, DUPLICATE_LINK_NAME, MULTIPLE_ROOTS, CYCLE).
    // Prefer the bracketed rule code if present; fall back to the first error.
    const first = errors[0]
    const codeMatch = first.match(/^\[([A-Z_]+)\]/)
    return {
      ok: false,
      code: codeMatch ? codeMatch[1] : 'VALIDATION_FAILED',
      message: errors.join(' | '),
    }
  }
  // De-dupe: the graph-wide validator may emit the same PORT_MISMATCH the
  // per-call check already produced.
  const merged = [...new Set([...extraWarnings, ...warnings])]
  return { ok: true, graph, warnings: merged, summary }
}

export function addLink(
  graph: AssemblyGraph,
  args: AddLinkArgs,
  ctx: ValidationContext,
): MutationResult {
  if (!ctx.findPreset(args.component_id)) {
    return {
      ok: false,
      code: 'UNKNOWN_COMPONENT',
      message: `component_id "${args.component_id}" is not in the preset library`,
      suggested_repair: 'pick a component_id from the catalog',
    }
  }

  const next = cloneAssemblyGraph(graph)
  const parent = next.components.find(c => c.link_name === args.parent_link)
  if (!parent) {
    return {
      ok: false,
      code: 'UNKNOWN_PARENT',
      message: `parent_link "${args.parent_link}" does not exist in the current graph`,
      suggested_repair: 'pass parent_link = one of the existing link_names',
    }
  }
  if (next.components.some(c => c.link_name === args.link_name)) {
    return {
      ok: false,
      code: 'DUPLICATE_LINK',
      message: `link_name "${args.link_name}" already exists`,
      suggested_repair: 'pick a unique link_name (convention: <component_id>_<N>)',
    }
  }

  const child: AssemblyComponent = {
    link_name: args.link_name,
    component_id: args.component_id,
    attach_to: args.parent_link,
    attach_face: args.attach_face || 'top',
    joint_type: args.joint_type ?? 'fixed',
    joint_axis: args.joint_axis ?? 'z',
    length_mm: args.length_mm,
    orientation: args.orientation,
    elevation_angle: args.elevation_angle,
    attach_rpy: args.attach_rpy,
    attach_connector: args.attach_connector,
    mate_connector: args.mate_connector,
    mate_type: args.mate_type,
  }

  // Pre-resolve connector check: runs only when the AI opted into named-
  // connector fields. Catches the dev-throw class (urdfAssembly.ts:2048) here
  // so the tool-call edit loop can self-correct in the same turn instead of
  // hard-crashing the build.
  const connErr = _checkConnectorReferences(ctx, parent, child)
  if (connErr) return connErr

  const portWarning = _portMismatchWarning(ctx, parent, child)

  next.components.push(child)
  return _validateAndRespond(
    next, ctx,
    `added ${child.link_name} (${child.component_id}) on ${args.parent_link}.${child.attach_face}`,
    portWarning ? [portWarning] : [],
  )
}

export function attachSensor(
  graph: AssemblyGraph,
  args: AttachSensorArgs,
  ctx: ValidationContext,
): MutationResult {
  if (!args.component_id.startsWith('sensor_')) {
    return {
      ok: false,
      code: 'NOT_A_SENSOR',
      message: `attach_sensor expects a sensor_* preset; got "${args.component_id}"`,
      suggested_repair: 'use add_link for non-sensor components',
    }
  }
  // Sensors are always fixed — rotating joints under a sensor mean the
  // camera/imu drifts with joint state, which is almost never the intent.
  return addLink(graph, {
    link_name: args.link_name,
    parent_link: args.parent_link,
    component_id: args.component_id,
    attach_face: args.mount_face,
    joint_type: 'fixed',
    joint_axis: 'z',
    elevation_angle: args.elevation_angle,
  }, ctx)
}

export function replaceComponent(
  graph: AssemblyGraph,
  args: ReplaceComponentArgs,
  ctx: ValidationContext,
): MutationResult {
  if (!ctx.findPreset(args.new_component_id)) {
    return {
      ok: false,
      code: 'UNKNOWN_COMPONENT',
      message: `component_id "${args.new_component_id}" is not in the preset library`,
    }
  }
  const next = cloneAssemblyGraph(graph)
  const target = next.components.find(c => c.link_name === args.link_name)
  if (!target) {
    return {
      ok: false,
      code: 'UNKNOWN_LINK',
      message: `link_name "${args.link_name}" does not exist`,
    }
  }
  const prevId = target.component_id
  target.component_id = args.new_component_id

  const parent = next.components.find(c => c.link_name === target.attach_to)

  // The new preset may not author the connector ids the existing component
  // referenced — re-validate against the swapped preset.
  const connErr = _checkConnectorReferences(ctx, parent, target)
  if (connErr) return connErr

  const portWarning = _portMismatchWarning(ctx, parent, target)

  return _validateAndRespond(
    next, ctx,
    `replaced ${args.link_name}: ${prevId} → ${args.new_component_id}`,
    portWarning ? [portWarning] : [],
  )
}

export function setJoint(
  graph: AssemblyGraph,
  args: SetJointArgs,
  ctx: ValidationContext,
): MutationResult {
  const validTypes = new Set(['fixed', 'revolute', 'prismatic', 'continuous'])
  if (!validTypes.has(args.joint_type)) {
    return {
      ok: false,
      code: 'BAD_JOINT_TYPE',
      message: `joint_type must be one of ${[...validTypes].join(', ')}; got "${args.joint_type}"`,
    }
  }
  const next = cloneAssemblyGraph(graph)
  const target = next.components.find(c => c.link_name === args.link_name)
  if (!target) {
    return {
      ok: false,
      code: 'UNKNOWN_LINK',
      message: `link_name "${args.link_name}" does not exist`,
    }
  }
  target.joint_type = args.joint_type
  if (args.joint_axis !== undefined) target.joint_axis = args.joint_axis
  if (args.attach_rpy !== undefined) target.attach_rpy = args.attach_rpy

  return _validateAndRespond(
    next, ctx,
    `joint on ${args.link_name} set to ${args.joint_type}` +
      (args.joint_axis ? ` axis=${args.joint_axis}` : ''),
  )
}

export function removeLink(
  graph: AssemblyGraph,
  args: RemoveLinkArgs,
  ctx: ValidationContext,
): MutationResult {
  const next = cloneAssemblyGraph(graph)
  const target = next.components.find(c => c.link_name === args.link_name)
  if (!target) {
    return {
      ok: false,
      code: 'UNKNOWN_LINK',
      message: `link_name "${args.link_name}" does not exist`,
    }
  }
  if (target.attach_to === null) {
    return {
      ok: false,
      code: 'ROOT_REMOVAL',
      message: `cannot remove root link "${args.link_name}" — every robot needs a base`,
      suggested_repair: 'use replace_component to swap the base, not remove_link',
    }
  }

  const directChildren = next.components.filter(c => c.attach_to === args.link_name)
  if (args.reparent_children && directChildren.length > 0) {
    // Graft the children onto the removed link's parent (preserves attach_face —
    // may produce overlaps; the placement engine handles spacing).
    for (const child of directChildren) child.attach_to = target.attach_to
    next.components = next.components.filter(c => c.link_name !== args.link_name)
    return _validateAndRespond(
      next, ctx,
      `removed ${args.link_name}, reparented ${directChildren.length} child(ren) to ${target.attach_to}`,
    )
  }

  // Default: cascade-delete the whole subtree (matches applyTopologyOps' remove op).
  const toRemove = new Set<string>([args.link_name])
  let changed = true
  while (changed) {
    changed = false
    for (const c of next.components) {
      if (c.attach_to && toRemove.has(c.attach_to) && !toRemove.has(c.link_name)) {
        toRemove.add(c.link_name)
        changed = true
      }
    }
  }
  const removedCount = toRemove.size
  next.components = next.components.filter(c => !toRemove.has(c.link_name))
  return _validateAndRespond(
    next, ctx,
    `removed ${args.link_name} and ${removedCount - 1} descendant(s)`,
  )
}

/** Thin dispatcher — routes a discriminated `GraphMutation` to the right mutator.
 * Python-side tool dispatch goes through here so there's a single table for
 * (tool_name ↔ mutator) instead of per-call if/else chains. */
export function applyMutation(
  graph: AssemblyGraph,
  mutation: GraphMutation,
  ctx: ValidationContext,
): MutationResult {
  switch (mutation.kind) {
    case 'add_link':          return addLink(graph, mutation.args, ctx)
    case 'attach_sensor':     return attachSensor(graph, mutation.args, ctx)
    case 'replace_component': return replaceComponent(graph, mutation.args, ctx)
    case 'set_joint':         return setJoint(graph, mutation.args, ctx)
    case 'remove_link':       return removeLink(graph, mutation.args, ctx)
  }
}
