import './style.css'
import * as THREE from 'three'
import { OrbitControls } from 'three/addons/controls/OrbitControls.js'

// ── Sample URDF ──────────────────────────────────────────────────────────────

const SAMPLE_URDF = `<?xml version="1.0"?>
<!-- 2-DOF arm: base_link → link1 → link2 -->
<!-- Generated by Vector -->
<robot name="simple_arm">

  <!-- base_link: fixed mounting plate -->
  <!-- mass: 0.5 kg | cylindrical, 150mm dia -->
  <link name="base_link">
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <geometry><cylinder radius="0.075" length="0.06"/></geometry>
    </visual>
  </link>

  <!-- link1: upper arm, 500mm, 0.3 kg -->
  <link name="link1">
    <inertial>
      <mass value="0.3"/>
      <inertia ixx="0.006" iyy="0.006" izz="0.001"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <geometry><box size="0.07 0.48 0.07"/></geometry>
    </visual>
  </link>

  <!-- joint1: revolute, z-axis, ±180° -->
  <!-- actuator: Dynamixel XH430 — 1.5 Nm continuous -->
  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0.06 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14"
           effort="1.5" velocity="2.0"/>
  </joint>

  <!-- link2: forearm, 400mm, 0.2 kg -->
  <link name="link2">
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.003" iyy="0.003" izz="0.0005"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <geometry><box size="0.06 0.38 0.06"/></geometry>
    </visual>
  </link>

  <!-- joint2: revolute, y-axis, ±120° — elbow -->
  <!-- actuator: Dynamixel XM540 — 10 Nm peak -->
  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0.48 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.09" upper="2.09"
           effort="10.0" velocity="1.5"/>
  </joint>

</robot>`

// ── Editor setup ─────────────────────────────────────────────────────────────

const editor = document.getElementById('editor') as HTMLTextAreaElement
const lineNumbers = document.getElementById('line-numbers') as HTMLDivElement
const cursorPos = document.getElementById('cursor-pos') as HTMLSpanElement

editor.value = SAMPLE_URDF

function updateLineNumbers() {
  const lines = editor.value.split('\n').length
  let html = ''
  for (let i = 1; i <= lines; i++) {
    html += i + '\n'
  }
  lineNumbers.textContent = html
}

function updateCursorPos() {
  const val = editor.value.substring(0, editor.selectionStart)
  const line = val.split('\n').length
  const col = val.split('\n').pop()!.length + 1
  cursorPos.textContent = `Ln ${line}, Col ${col}`
}

editor.addEventListener('input', updateLineNumbers)
editor.addEventListener('scroll', () => { lineNumbers.scrollTop = editor.scrollTop })
editor.addEventListener('click', updateCursorPos)
editor.addEventListener('keyup', updateCursorPos)

// Handle tab in editor
editor.addEventListener('keydown', (e) => {
  if (e.key === 'Tab') {
    e.preventDefault()
    const start = editor.selectionStart
    const end = editor.selectionEnd
    editor.value = editor.value.substring(0, start) + '  ' + editor.value.substring(end)
    editor.selectionStart = editor.selectionEnd = start + 2
    updateLineNumbers()
  }
})

updateLineNumbers()

// ── Three.js Viewport ────────────────────────────────────────────────────────

const canvas = document.getElementById('viewport') as HTMLCanvasElement
const viewportPanel = document.getElementById('viewport-panel') as HTMLDivElement

const renderer = new THREE.WebGLRenderer({ canvas, antialias: true })
renderer.setPixelRatio(window.devicePixelRatio)
renderer.setClearColor(0x0d0d0d)
renderer.shadowMap.enabled = true
renderer.shadowMap.type = THREE.PCFSoftShadowMap

const scene = new THREE.Scene()

const camera = new THREE.PerspectiveCamera(55, 1, 0.01, 100)
camera.position.set(1.5, 1.4, 1.8)
camera.lookAt(0, 0.4, 0)

const controls = new OrbitControls(camera, canvas)
controls.enableDamping = true
controls.dampingFactor = 0.08
controls.target.set(0, 0.4, 0)

// Ground grid
const grid = new THREE.GridHelper(6, 30, 0x1a1a1a, 0x141414)
scene.add(grid)

// Ground plane (for shadows)
const groundGeo = new THREE.PlaneGeometry(6, 6)
const groundMat = new THREE.ShadowMaterial({ opacity: 0.2 })
const ground = new THREE.Mesh(groundGeo, groundMat)
ground.rotation.x = -Math.PI / 2
ground.receiveShadow = true
scene.add(ground)

// Origin axes
const originAxes = new THREE.AxesHelper(0.2)
scene.add(originAxes)

// Lights
const ambient = new THREE.AmbientLight(0xffffff, 0.3)
scene.add(ambient)

const keyLight = new THREE.DirectionalLight(0xffffff, 1.0)
keyLight.position.set(3, 6, 4)
keyLight.castShadow = true
keyLight.shadow.mapSize.set(1024, 1024)
keyLight.shadow.camera.near = 0.5
keyLight.shadow.camera.far = 20
scene.add(keyLight)

const fillLight = new THREE.DirectionalLight(0x6688cc, 0.3)
fillLight.position.set(-3, 2, -2)
scene.add(fillLight)

const rimLight = new THREE.DirectionalLight(0xffffff, 0.2)
rimLight.position.set(0, 1, -4)
scene.add(rimLight)

// Materials
const linkMat = new THREE.MeshPhongMaterial({ color: 0x2a6dd9, shininess: 60, specular: 0x222244 })
const linkWireMat = new THREE.MeshBasicMaterial({ color: 0x4a9eff, wireframe: true, transparent: true, opacity: 0.15 })
const jointMat = new THREE.MeshPhongMaterial({ color: 0xff6b35, shininess: 80, specular: 0x442222 })
const comMat = new THREE.MeshPhongMaterial({ color: 0xe5c07b, emissive: 0x332200 })

// Robot group
const robot = new THREE.Group()
scene.add(robot)

// Wireframe overlay group
const wireframeGroup = new THREE.Group()
wireframeGroup.visible = false
robot.add(wireframeGroup)

// base_link
const baseMesh = new THREE.Mesh(new THREE.CylinderGeometry(0.15, 0.15, 0.06, 32), linkMat)
baseMesh.position.y = 0.03
baseMesh.castShadow = true
robot.add(baseMesh)
wireframeGroup.add(new THREE.Mesh(new THREE.CylinderGeometry(0.15, 0.15, 0.06, 32), linkWireMat).translateY(0.03))

// link1
const link1Mesh = new THREE.Mesh(new THREE.BoxGeometry(0.07, 0.48, 0.07), linkMat)
link1Mesh.position.y = 0.06 + 0.24
link1Mesh.castShadow = true
robot.add(link1Mesh)
wireframeGroup.add(new THREE.Mesh(new THREE.BoxGeometry(0.07, 0.48, 0.07), linkWireMat).translateY(0.06 + 0.24))

// link2 (angled)
const link2Mesh = new THREE.Mesh(new THREE.BoxGeometry(0.06, 0.38, 0.06), linkMat)
link2Mesh.position.set(0.12, 0.06 + 0.48 + 0.15, 0)
link2Mesh.rotation.z = -Math.PI / 6
link2Mesh.castShadow = true
robot.add(link2Mesh)
const link2Wire = new THREE.Mesh(new THREE.BoxGeometry(0.06, 0.38, 0.06), linkWireMat)
link2Wire.position.copy(link2Mesh.position)
link2Wire.rotation.copy(link2Mesh.rotation)
wireframeGroup.add(link2Wire)

// Joint spheres
function addJoint(x: number, y: number, z: number, axisDir: THREE.Vector3) {
  const sphere = new THREE.Mesh(new THREE.SphereGeometry(0.04, 16, 16), jointMat)
  sphere.position.set(x, y, z)
  sphere.castShadow = true
  robot.add(sphere)

  // Joint axis line
  const axisLen = 0.15
  const points = [
    new THREE.Vector3().copy(axisDir).multiplyScalar(-axisLen),
    new THREE.Vector3().copy(axisDir).multiplyScalar(axisLen),
  ]
  const lineGeo = new THREE.BufferGeometry().setFromPoints(points)
  const lineMat = new THREE.LineBasicMaterial({ color: 0xff6b35, transparent: true, opacity: 0.6 })
  const axisLine = new THREE.Line(lineGeo, lineMat)
  axisLine.position.set(x, y, z)
  robot.add(axisLine)

  // Rotation ring
  const ringGeo = new THREE.TorusGeometry(0.06, 0.003, 8, 32)
  const ringMat = new THREE.MeshBasicMaterial({ color: 0xff6b35, transparent: true, opacity: 0.25 })
  const ring = new THREE.Mesh(ringGeo, ringMat)
  ring.position.set(x, y, z)
  // Orient ring perpendicular to axis
  if (axisDir.z > 0.5) ring.rotation.x = 0 // already correct for Z
  else if (axisDir.y > 0.5) ring.rotation.x = Math.PI / 2
  else ring.rotation.z = Math.PI / 2
  robot.add(ring)
}

addJoint(0, 0.06, 0, new THREE.Vector3(0, 0, 1))       // joint1: Z axis
addJoint(0, 0.06 + 0.48, 0, new THREE.Vector3(0, 1, 0)) // joint2: Y axis

// Link frame axes (small RGB arrows at each link)
function addFrameAxes(x: number, y: number, z: number) {
  const axes = new THREE.AxesHelper(0.08)
  axes.position.set(x, y, z)
  robot.add(axes)
}
addFrameAxes(0, 0.03, 0)       // base_link
addFrameAxes(0, 0.06, 0)       // link1 origin
addFrameAxes(0, 0.06 + 0.48, 0) // link2 origin

// CoM marker
const comGroup = new THREE.Group()
const comY = (0.5 * 0.03 + 0.3 * 0.3 + 0.2 * 0.73) / (0.5 + 0.3 + 0.2) // weighted average
const comDiamond = new THREE.Mesh(new THREE.OctahedronGeometry(0.03), comMat)
comDiamond.position.set(0.024, comY, 0)
comGroup.add(comDiamond)

// CoM vertical projection line
const comLinePts = [new THREE.Vector3(0.024, comY, 0), new THREE.Vector3(0.024, 0, 0)]
const comLineGeo = new THREE.BufferGeometry().setFromPoints(comLinePts)
const comLineMat = new THREE.LineDashedMaterial({ color: 0xe5c07b, dashSize: 0.02, gapSize: 0.01, transparent: true, opacity: 0.5 })
const comLine = new THREE.Line(comLineGeo, comLineMat)
comLine.computeLineDistances()
comGroup.add(comLine)
robot.add(comGroup)

// ── Viewport controls ────────────────────────────────────────────────────────

const toggleWireframe = document.getElementById('toggle-wireframe') as HTMLButtonElement
const toggleAxesBtn = document.getElementById('toggle-axes') as HTMLButtonElement
const toggleCom = document.getElementById('toggle-com') as HTMLButtonElement

toggleWireframe.addEventListener('click', () => {
  wireframeGroup.visible = !wireframeGroup.visible
  toggleWireframe.classList.toggle('active', wireframeGroup.visible)
})

let frameAxesVisible = true
toggleAxesBtn.classList.add('active')
toggleAxesBtn.addEventListener('click', () => {
  frameAxesVisible = !frameAxesVisible
  robot.children.forEach(c => { if (c instanceof THREE.AxesHelper) c.visible = frameAxesVisible })
  originAxes.visible = frameAxesVisible
  toggleAxesBtn.classList.toggle('active', frameAxesVisible)
})

toggleCom.classList.add('active')
toggleCom.addEventListener('click', () => {
  comGroup.visible = !comGroup.visible
  toggleCom.classList.toggle('active', comGroup.visible)
})

// ── Sim mode ─────────────────────────────────────────────────────────────────

const simToggle = document.getElementById('sim-toggle') as HTMLButtonElement
const simBar = document.getElementById('sim-bar') as HTMLDivElement
const simPlay = document.getElementById('sim-play') as HTMLButtonElement
const simPause = document.getElementById('sim-pause') as HTMLButtonElement
const simReset = document.getElementById('sim-reset') as HTMLButtonElement
const simProgress = document.getElementById('sim-progress') as HTMLDivElement
const simTimeEl = document.getElementById('sim-time') as HTMLSpanElement
const viewportLabel = document.getElementById('viewport-label') as HTMLSpanElement

let simRunning = false
let simActive = false
let simTime = 0

simToggle.addEventListener('click', () => {
  simActive = !simActive
  simBar.classList.toggle('hidden', !simActive)
  simToggle.classList.toggle('running', simActive)
  simToggle.textContent = simActive ? 'Exit Sim' : 'Simulate'
  viewportLabel.textContent = simActive ? 'Simulation' : '3D Preview'
  if (!simActive) { simRunning = false; simTime = 0; updateSimUI() }
})

simPlay.addEventListener('click', () => { simRunning = true; updateSimUI() })
simPause.addEventListener('click', () => { simRunning = false; updateSimUI() })
simReset.addEventListener('click', () => { simRunning = false; simTime = 0; updateSimUI() })

function updateSimUI() {
  simPlay.classList.toggle('active', simRunning)
  simPause.classList.toggle('active', !simRunning && simActive)
  simTimeEl.textContent = simTime.toFixed(3) + 's'
  simProgress.style.width = `${Math.min((simTime / 10) * 100, 100)}%`
}

// ── Resize ───────────────────────────────────────────────────────────────────

function resize() {
  const rect = canvas.parentElement!.getBoundingClientRect()
  const headerH = document.getElementById('viewport-header')!.offsetHeight
  const simBarH = simActive ? simBar.offsetHeight : 0
  const w = rect.width
  const h = rect.height - headerH - simBarH
  renderer.setSize(w, h)
  camera.aspect = w / h
  camera.updateProjectionMatrix()
}

resize()
window.addEventListener('resize', resize)

// ── Animate ──────────────────────────────────────────────────────────────────

function animate() {
  requestAnimationFrame(animate)
  controls.update()

  // Sim animation: gentle joint oscillation
  if (simRunning) {
    simTime += 1 / 60
    updateSimUI()

    // Animate link2 elbow angle
    const t = simTime * 1.5
    link2Mesh.rotation.z = -Math.PI / 6 + Math.sin(t) * 0.3
    link2Wire.rotation.z = link2Mesh.rotation.z

    // Subtle base rotation
    baseMesh.rotation.y = Math.sin(t * 0.7) * 0.15
  }

  renderer.render(scene, camera)
}
animate()

// ── Draggable split ──────────────────────────────────────────────────────────

const handle = document.getElementById('resize-handle') as HTMLDivElement
const editorPanel = document.getElementById('editor-panel') as HTMLDivElement
const main = document.getElementById('main') as HTMLDivElement

let dragging = false

handle.addEventListener('mousedown', () => {
  dragging = true
  handle.classList.add('dragging')
  document.body.style.cursor = 'col-resize'
  document.body.style.userSelect = 'none'
})

document.addEventListener('mousemove', (e) => {
  if (!dragging) return
  const rect = main.getBoundingClientRect()
  const pct = ((e.clientX - rect.left) / rect.width) * 100
  editorPanel.style.width = `${Math.min(Math.max(pct, 15), 85)}%`
  resize()
})

document.addEventListener('mouseup', () => {
  if (!dragging) return
  dragging = false
  handle.classList.remove('dragging')
  document.body.style.cursor = ''
  document.body.style.userSelect = ''
})

// ── Sidebar ──────────────────────────────────────────────────────────────────

// Collapsible sections
document.querySelectorAll('.sb-header').forEach(header => {
  header.addEventListener('click', () => {
    const targetId = (header as HTMLElement).dataset.target!
    const list = document.getElementById(targetId)!
    const arrow = header.querySelector('.arrow')!
    const isHidden = list.style.display === 'none'
    list.style.display = isHidden ? '' : 'none'
    arrow.textContent = isHidden ? '\u25BE' : '\u25B8'
  })
})

// Preset drag hint
document.querySelectorAll('.preset-item').forEach(item => {
  item.addEventListener('click', () => {
    const name = (item as HTMLElement).dataset.preset!
    commandInput.value = `add ${name.replace(/-/g, ' ')} to the robot`
    commandInput.focus()
  })
})

// ── Command bar ──────────────────────────────────────────────────────────────

const commandInput = document.getElementById('command-input') as HTMLInputElement
const output = document.getElementById('command-output') as HTMLDivElement
const outputText = document.getElementById('output-text') as HTMLDivElement
const acceptBtn = document.querySelector('.action-btn.accept') as HTMLButtonElement
const rejectBtn = document.querySelector('.action-btn.reject') as HTMLButtonElement
const statusEl = document.getElementById('status') as HTMLSpanElement

// Ctrl+K shortcut
document.addEventListener('keydown', (e) => {
  if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
    e.preventDefault()
    commandInput.focus()
  }
})

// Smart responses based on keywords
const RESPONSES: Record<string, string> = {
  'leg': `Added left_leg and right_leg subtrees at base_link.
  Hip joints: revolute, ±90°, 50 Nm (matched to torso mass).
  Knee joints: revolute, 0–120°, 30 Nm.
  +4 links, +4 joints, +8 params modified.`,

  'arm': `Extended link2 length from 400mm → 550mm.
  Updated inertia tensor for new mass distribution.
  Joint2 torque limit adjusted: 10 Nm → 14 Nm.
  CoM shifted +32mm — still within support polygon.`,

  'camera': `Added depth_camera link at head (RealSense D435 preset).
  Fixed joint, facing forward, 10° downward tilt.
  FOV: 87° × 58°, range: 0.1–10m.
  +1 link, +1 joint, +1 sensor definition.`,

  'gripper': `Added parallel_jaw_gripper at link2 end-effector.
  2-finger design, 85mm max opening.
  Grip force: 40N continuous (Robotiq preset).
  +3 links, +3 joints (1 fixed + 2 prismatic).`,

  'mirror': `Mirrored right_arm subtree → left_arm.
  All joint axes reflected across YZ plane.
  Preserved torque limits and inertia tensors.
  +3 links, +2 joints created.`,

  'stiffen': `Increased joint damping coefficients:
  joint1: 0.5 → 2.0 Nm·s/rad
  joint2: 0.3 → 1.5 Nm·s/rad
  This should reduce oscillation in sim.`,
}

function getResponse(cmd: string): string {
  const lower = cmd.toLowerCase()
  for (const [key, resp] of Object.entries(RESPONSES)) {
    if (lower.includes(key)) return resp
  }
  return `Analyzing: "${cmd}"
  Computed kinematic graph diff.
  2 nodes modified, 0 added, 0 removed.
  Validation: all checks passed.`
}

// Typewriter effect
function typeText(text: string, el: HTMLDivElement, callback?: () => void) {
  el.textContent = ''
  el.classList.add('typing-cursor')
  let i = 0
  const interval = setInterval(() => {
    el.textContent += text[i]
    i++
    if (i >= text.length) {
      clearInterval(interval)
      el.classList.remove('typing-cursor')
      if (callback) callback()
    }
  }, 12)
}

commandInput.addEventListener('keydown', (e) => {
  if (e.key !== 'Enter') return
  const cmd = commandInput.value.trim()
  if (!cmd) return

  commandInput.value = ''
  statusEl.textContent = 'thinking...'
  statusEl.style.color = '#e5c07b'
  output.classList.remove('hidden')
  outputText.textContent = ''

  // Simulate AI delay
  const delay = 400 + Math.random() * 600
  setTimeout(() => {
    const resp = `↳ ${getResponse(cmd)}`
    typeText(resp, outputText, () => {
      statusEl.textContent = 'ready'
      statusEl.style.color = ''
    })
  }, delay)
})

acceptBtn.addEventListener('click', () => {
  outputText.textContent = '✓ Changes applied to robot.urdf'
  outputText.style.color = '#4ec9b0'
  setTimeout(() => {
    output.classList.add('hidden')
    outputText.style.color = ''
  }, 1500)
})

rejectBtn.addEventListener('click', () => {
  outputText.textContent = '✗ Changes discarded.'
  outputText.style.color = '#f44336'
  setTimeout(() => {
    output.classList.add('hidden')
    outputText.style.color = ''
  }, 1000)
})
