import './style.css'
import * as THREE from 'three'
import { OrbitControls } from 'three/addons/controls/OrbitControls.js'

// ── Sample URDF ──────────────────────────────────────────────────────────────

const SAMPLE_URDF = `<?xml version="1.0"?>
<!-- Vector — 3-DOF Robot Arm with Gripper -->
<!-- Generated by Vector AI | Claude Sonnet 4.6 -->
<robot name="simple_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ════════════════════════════════════════════ -->
  <!-- base_link: fixed mounting plate              -->
  <!-- mass: 1.2 kg | steel, 300mm dia, 50mm tall  -->
  <!-- ════════════════════════════════════════════ -->
  <link name="base_link">
    <inertial>
      <mass value="1.2"/>
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <inertia ixx="0.003" iyy="0.003" izz="0.005"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.15" length="0.05"/>
      </geometry>
      <material name="dark_steel">
        <color rgba="0.18 0.2 0.25 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.15" length="0.05"/>
      </geometry>
    </collision>
  </link>

  <!-- ════════════════════════════════════════════ -->
  <!-- shoulder_link: servo housing                 -->
  <!-- actuator: Dynamixel XM540 — 10 Nm peak      -->
  <!-- ════════════════════════════════════════════ -->
  <link name="shoulder_link">
    <inertial>
      <mass value="0.18"/>
      <inertia ixx="0.0001" iyy="0.0001" izz="0.0001"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.035" length="0.055"/>
      </geometry>
      <material name="servo_black">
        <color rgba="0.12 0.12 0.14 1"/>
      </material>
    </visual>
  </link>

  <!-- joint: shoulder_pan — rotates around Z -->
  <joint name="shoulder_pan" type="revolute">
    <parent link="base_link"/>
    <child link="shoulder_link"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14"
           effort="10.0" velocity="2.0"/>
    <dynamics damping="0.5" friction="0.1"/>
  </joint>

  <!-- ════════════════════════════════════════════ -->
  <!-- upper_arm: 350mm aluminum tube, 0.4 kg      -->
  <!-- cross-section: 70×70mm square tube           -->
  <!-- ════════════════════════════════════════════ -->
  <link name="upper_arm">
    <inertial>
      <mass value="0.4"/>
      <origin xyz="0 0 0.175" rpy="0 0 0"/>
      <inertia ixx="0.004" iyy="0.004" izz="0.0005"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <geometry>
        <box size="0.065 0.065 0.35"/>
      </geometry>
      <material name="arm_blue">
        <color rgba="0.16 0.43 0.85 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.065 0.065 0.35"/>
      </geometry>
    </collision>
  </link>

  <!-- joint: shoulder_lift — rotates around Y -->
  <joint name="shoulder_lift" type="revolute">
    <parent link="shoulder_link"/>
    <child link="upper_arm"/>
    <origin xyz="0 0 0.03" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="2.36"
           effort="10.0" velocity="1.5"/>
    <dynamics damping="0.7" friction="0.15"/>
  </joint>

  <!-- ════════════════════════════════════════════ -->
  <!-- elbow_link: servo housing                    -->
  <!-- actuator: Dynamixel XH430 — 1.5 Nm          -->
  <!-- ════════════════════════════════════════════ -->
  <link name="elbow_link">
    <inertial>
      <mass value="0.12"/>
      <inertia ixx="0.00005" iyy="0.00005" izz="0.00005"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="0.03" length="0.05"/>
      </geometry>
      <material name="servo_black"/>
    </visual>
  </link>

  <joint name="elbow" type="revolute">
    <parent link="upper_arm"/>
    <child link="elbow_link"/>
    <origin xyz="0 0 0.35" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.36" upper="2.36"
           effort="1.5" velocity="2.5"/>
    <dynamics damping="0.3" friction="0.05"/>
  </joint>

  <!-- ════════════════════════════════════════════ -->
  <!-- forearm: 280mm, thinner, 0.25 kg             -->
  <!-- ════════════════════════════════════════════ -->
  <link name="forearm">
    <inertial>
      <mass value="0.25"/>
      <origin xyz="0 0 0.14" rpy="0 0 0"/>
      <inertia ixx="0.002" iyy="0.002" izz="0.0003"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <geometry>
        <box size="0.055 0.055 0.28"/>
      </geometry>
      <material name="arm_blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.055 0.055 0.28"/>
      </geometry>
    </collision>
  </link>

  <joint name="forearm_attach" type="fixed">
    <parent link="elbow_link"/>
    <child link="forearm"/>
    <origin xyz="0 0 0.03" rpy="0 0 0"/>
  </joint>

  <!-- ════════════════════════════════════════════ -->
  <!-- wrist + gripper                              -->
  <!-- parallel jaw, 85mm max opening, 40N grip     -->
  <!-- ════════════════════════════════════════════ -->
  <link name="wrist">
    <inertial>
      <mass value="0.08"/>
      <inertia ixx="0.00002" iyy="0.00002" izz="0.00002"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <geometry>
        <sphere radius="0.025"/>
      </geometry>
      <material name="servo_black"/>
    </visual>
  </link>

  <joint name="wrist_attach" type="fixed">
    <parent link="forearm"/>
    <child link="wrist"/>
    <origin xyz="0 0 0.28" rpy="0 0 0"/>
  </joint>

  <link name="gripper_base">
    <inertial>
      <mass value="0.06"/>
      <inertia ixx="0.00001" iyy="0.00001" izz="0.00001"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <geometry>
        <box size="0.06 0.02 0.03"/>
      </geometry>
      <material name="dark_steel"/>
    </visual>
  </link>

  <joint name="gripper_attach" type="fixed">
    <parent link="wrist"/>
    <child link="gripper_base"/>
    <origin xyz="0 0 0.025" rpy="0 0 0"/>
  </joint>

  <link name="finger_left">
    <inertial>
      <mass value="0.02"/>
      <inertia ixx="0.000005" iyy="0.000005" izz="0.000005"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <geometry>
        <box size="0.008 0.06 0.025"/>
      </geometry>
      <material name="arm_blue"/>
    </visual>
  </link>

  <joint name="finger_left_joint" type="prismatic">
    <parent link="gripper_base"/>
    <child link="finger_left"/>
    <origin xyz="-0.02 0.04 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-0.01" upper="0.02" effort="40" velocity="0.1"/>
  </joint>

  <link name="finger_right">
    <inertial>
      <mass value="0.02"/>
      <inertia ixx="0.000005" iyy="0.000005" izz="0.000005"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
    <visual>
      <geometry>
        <box size="0.008 0.06 0.025"/>
      </geometry>
      <material name="arm_blue"/>
    </visual>
  </link>

  <joint name="finger_right_joint" type="prismatic">
    <parent link="gripper_base"/>
    <child link="finger_right"/>
    <origin xyz="0.02 0.04 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-0.02" upper="0.01" effort="40" velocity="0.1"/>
  </joint>

</robot>`

// ── Syntax Highlighting ──────────────────────────────────────────────────────

function highlightXML(raw: string): string {
  const esc = raw.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  return esc.replace(
    /(&lt;!--[\s\S]*?--&gt;)|(&lt;\?[\s\S]*?\?&gt;)|("(?:[^"\\]|\\.)*")|(&lt;\/?)([\w:.-]+)|([\w:.-]+)(=)/g,
    (_match, comment, decl, str, tagOpen, tagName, attrName, eq) => {
      if (comment) return `<span class="hl-comment">${comment}</span>`
      if (decl) return `<span class="hl-decl">${decl}</span>`
      if (str) return `<span class="hl-string">${str}</span>`
      if (tagOpen && tagName) return `${tagOpen}<span class="hl-tag">${tagName}</span>`
      if (attrName && eq) return `<span class="hl-attr">${attrName}</span>${eq}`
      return _match
    }
  )
}

// ── Editor ───────────────────────────────────────────────────────────────────

const editor = document.getElementById('editor') as HTMLTextAreaElement
const highlightLayer = document.getElementById('highlight-layer') as HTMLPreElement
const lineNumbers = document.getElementById('line-numbers') as HTMLDivElement
const cursorPos = document.getElementById('cursor-pos') as HTMLSpanElement

editor.value = SAMPLE_URDF

function updateHighlight() {
  highlightLayer.innerHTML = highlightXML(editor.value) + '\n'
}

function updateLineNumbers() {
  const lines = editor.value.split('\n').length
  const nums: string[] = []
  for (let i = 1; i <= lines; i++) nums.push(String(i))
  lineNumbers.textContent = nums.join('\n')
}

function updateCursorPos() {
  const val = editor.value.substring(0, editor.selectionStart)
  const line = val.split('\n').length
  const col = val.split('\n').pop()!.length + 1
  cursorPos.textContent = `Ln ${line}, Col ${col}`
}

function syncScroll() {
  highlightLayer.scrollTop = editor.scrollTop
  highlightLayer.scrollLeft = editor.scrollLeft
  lineNumbers.scrollTop = editor.scrollTop
}

editor.addEventListener('input', () => { updateHighlight(); updateLineNumbers() })
editor.addEventListener('scroll', syncScroll)
editor.addEventListener('click', updateCursorPos)
editor.addEventListener('keyup', updateCursorPos)

editor.addEventListener('keydown', (e) => {
  if (e.key === 'Tab') {
    e.preventDefault()
    const s = editor.selectionStart, end = editor.selectionEnd
    editor.value = editor.value.substring(0, s) + '  ' + editor.value.substring(end)
    editor.selectionStart = editor.selectionEnd = s + 2
    updateHighlight()
    updateLineNumbers()
  }
})

updateHighlight()
updateLineNumbers()

// ── Tab switching ────────────────────────────────────────────────────────────

const SAMPLE_PRESETS = `{
  "actuators": {
    "dynamixel_xm540": {
      "name": "Dynamixel XM540-W270",
      "type": "servo",
      "torque_nm": 10.6,
      "speed_rpm": 46,
      "voltage": 12,
      "weight_g": 165,
      "resolution": 4096
    },
    "dynamixel_xh430": {
      "name": "Dynamixel XH430-W210",
      "type": "servo",
      "torque_nm": 2.7,
      "speed_rpm": 52,
      "voltage": 12,
      "weight_g": 82,
      "resolution": 4096
    }
  },
  "sensors": {
    "realsense_d435": {
      "name": "Intel RealSense D435",
      "type": "depth_camera",
      "depth_range_m": [0.2, 10.0],
      "resolution": "1280x720",
      "fps": 30,
      "fov_h_deg": 87,
      "weight_g": 72
    }
  }
}`

const SAMPLE_CONFIG = `# Vector Project Configuration
# Generated by Vector AI

project:
  name: simple_arm
  version: 0.1.0
  format: urdf

simulation:
  backend: mujoco
  timestep: 0.002
  gravity: [0, 0, -9.81]
  integrator: Euler

viewport:
  background: "#0c0c0c"
  grid_size: 8
  grid_divisions: 40
  show_axes: true
  show_com: false

export:
  mesh_format: stl
  coordinate_frame: z-up
  scale: 1.0
`

const fileContents: Record<string, string> = {
  'robot.urdf': SAMPLE_URDF,
  'presets.json': SAMPLE_PRESETS,
  'config.yaml': SAMPLE_CONFIG,
}

const fileTypes: Record<string, string> = {
  'robot.urdf': 'URDF',
  'presets.json': 'JSON',
  'config.yaml': 'YAML',
}

let activeFile = 'robot.urdf'
const fileTypeLabel = document.getElementById('file-type') as HTMLSpanElement
const tabs = document.querySelectorAll('#tab-bar .tab') as NodeListOf<HTMLDivElement>
const fileItems = document.querySelectorAll('.file-item') as NodeListOf<HTMLDivElement>

function switchToFile(filename: string) {
  // Save current content
  fileContents[activeFile] = editor.value

  activeFile = filename
  editor.value = fileContents[filename] || ''
  fileTypeLabel.textContent = fileTypes[filename] || 'TEXT'

  // Update tab active state
  tabs.forEach(tab => {
    tab.classList.toggle('active', tab.dataset.file === filename)
  })

  // Update explorer active state
  fileItems.forEach(item => {
    item.classList.toggle('active', item.textContent?.trim().endsWith(filename) || false)
  })

  // Update breadcrumb
  const bcItems = document.querySelectorAll('.bc-item')
  if (bcItems.length > 0) {
    bcItems[bcItems.length - 1].textContent = filename
  }

  updateHighlight()
  updateLineNumbers()
  updateCursorPos()
}

tabs.forEach(tab => {
  tab.addEventListener('click', (e) => {
    // Don't switch if clicking the close button
    if ((e.target as HTMLElement).classList.contains('tab-close')) return
    const file = tab.dataset.file
    if (file) switchToFile(file)
  })
})

fileItems.forEach(item => {
  item.addEventListener('click', () => {
    const text = item.textContent?.trim() || ''
    // Extract filename from the item text (might have dot prefix from fi-dot span)
    const filename = Object.keys(fileContents).find(f => text.endsWith(f))
    if (filename) switchToFile(filename)
  })
})

// ── Three.js ─────────────────────────────────────────────────────────────────

const canvas = document.getElementById('viewport') as HTMLCanvasElement
const viewportPanel = document.getElementById('viewport-panel') as HTMLDivElement

const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: false })
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2))
renderer.setClearColor(0x0c0c0c)
renderer.shadowMap.enabled = true
renderer.shadowMap.type = THREE.PCFSoftShadowMap
renderer.toneMapping = THREE.ACESFilmicToneMapping
renderer.toneMappingExposure = 1.1

const scene = new THREE.Scene()

// Subtle fog for depth
scene.fog = new THREE.FogExp2(0x0c0c0c, 0.3)

const camera = new THREE.PerspectiveCamera(50, 1, 0.01, 100)
camera.position.set(1.2, 1.0, 1.6)

const controls = new OrbitControls(camera, canvas)
controls.enableDamping = true
controls.dampingFactor = 0.06
controls.target.set(0, 0.35, 0)
controls.minDistance = 0.3
controls.maxDistance = 8

// ── Scene setup ──────────────────────────────────────────────────────────────

// Grid
const grid = new THREE.GridHelper(8, 40, 0x3a3a44, 0x2a2a32)
scene.add(grid)

// Ground shadow receiver
const groundMesh = new THREE.Mesh(
  new THREE.PlaneGeometry(8, 8),
  new THREE.ShadowMaterial({ opacity: 0.25 })
)
groundMesh.rotation.x = -Math.PI / 2
groundMesh.receiveShadow = true
scene.add(groundMesh)

// Origin axes
const originAxes = new THREE.AxesHelper(0.5)
scene.add(originAxes)

// Lights
scene.add(new THREE.AmbientLight(0xc8cce0, 0.4))

const keyLight = new THREE.DirectionalLight(0xffffff, 1.2)
keyLight.position.set(3, 6, 4)
keyLight.castShadow = true
keyLight.shadow.mapSize.set(2048, 2048)
keyLight.shadow.camera.near = 0.5
keyLight.shadow.camera.far = 20
keyLight.shadow.camera.left = -3
keyLight.shadow.camera.right = 3
keyLight.shadow.camera.top = 3
keyLight.shadow.camera.bottom = -3
keyLight.shadow.bias = -0.0005
scene.add(keyLight)

const fillLight = new THREE.DirectionalLight(0x6688cc, 0.4)
fillLight.position.set(-3, 2, -2)
scene.add(fillLight)

const rimLight = new THREE.DirectionalLight(0x8888ff, 0.25)
rimLight.position.set(0, 0.5, -4)
scene.add(rimLight)

// ── Materials ────────────────────────────────────────────────────────────────

const steelMat = new THREE.MeshStandardMaterial({
  color: 0x2a2e38, roughness: 0.4, metalness: 0.7,
})
const armMat = new THREE.MeshStandardMaterial({
  color: 0x2a6dd9, roughness: 0.35, metalness: 0.5,
})
const servoMat = new THREE.MeshStandardMaterial({
  color: 0x1a1a22, roughness: 0.5, metalness: 0.6,
})
const gripperMat = new THREE.MeshStandardMaterial({
  color: 0x3a7ae8, roughness: 0.3, metalness: 0.5,
})
const jointAccentMat = new THREE.MeshStandardMaterial({
  color: 0xff7b45, roughness: 0.4, metalness: 0.3, emissive: 0x331500,
})
const comMat = new THREE.MeshStandardMaterial({
  color: 0xe5c07b, roughness: 0.3, metalness: 0.2, emissive: 0x665500,
})
const wireMat = new THREE.MeshBasicMaterial({
  color: 0x4a9eff, wireframe: true, transparent: true, opacity: 0.12,
})

// ── Build robot (hierarchical) ───────────────────────────────────────────────

const robot = new THREE.Group()
scene.add(robot)

function makeShadowed(mesh: THREE.Mesh) {
  mesh.castShadow = true
  mesh.receiveShadow = true
  return mesh
}

// Base
const baseGroup = new THREE.Group()
robot.add(baseGroup)

const basePlate = makeShadowed(new THREE.Mesh(new THREE.CylinderGeometry(0.15, 0.16, 0.05, 48), steelMat))
basePlate.position.y = 0.025
baseGroup.add(basePlate)

// Base ring accent
const baseRing = new THREE.Mesh(new THREE.TorusGeometry(0.15, 0.005, 8, 48), jointAccentMat)
baseRing.rotation.x = Math.PI / 2
baseRing.position.y = 0.05
baseGroup.add(baseRing)

// Shoulder pivot (rotates around Y via shoulder_pan)
const shoulderPivot = new THREE.Group()
shoulderPivot.position.y = 0.05
baseGroup.add(shoulderPivot)

// Shoulder servo housing
const shoulderServo = makeShadowed(new THREE.Mesh(new THREE.CylinderGeometry(0.035, 0.035, 0.055, 24), servoMat))
shoulderServo.position.y = 0.0275
shoulderPivot.add(shoulderServo)

// Shoulder joint ring
const shoulderRing = new THREE.Mesh(new THREE.TorusGeometry(0.038, 0.004, 8, 24), jointAccentMat)
shoulderRing.rotation.x = Math.PI / 2
shoulderRing.position.y = 0.02
shoulderPivot.add(shoulderRing)

// Upper arm pivot (rotates around X for shoulder_lift)
const upperArmPivot = new THREE.Group()
upperArmPivot.position.y = 0.055
shoulderPivot.add(upperArmPivot)

// Upper arm
const upperArmMesh = makeShadowed(new THREE.Mesh(new THREE.BoxGeometry(0.065, 0.35, 0.065), armMat))
upperArmMesh.position.y = 0.175
upperArmPivot.add(upperArmMesh)

// Edge highlight strips on upper arm
const stripGeo = new THREE.BoxGeometry(0.002, 0.35, 0.067)
const stripMat = new THREE.MeshBasicMaterial({ color: 0x4a9eff, transparent: true, opacity: 0.15 })
const stripL = new THREE.Mesh(stripGeo, stripMat)
stripL.position.set(-0.033, 0.175, 0)
upperArmPivot.add(stripL)
const stripR = new THREE.Mesh(stripGeo, stripMat)
stripR.position.set(0.033, 0.175, 0)
upperArmPivot.add(stripR)

// Elbow pivot
const elbowPivot = new THREE.Group()
elbowPivot.position.y = 0.35
upperArmPivot.add(elbowPivot)

// Elbow servo
const elbowServo = makeShadowed(new THREE.Mesh(new THREE.CylinderGeometry(0.03, 0.03, 0.05, 24), servoMat))
elbowServo.position.y = 0.025
elbowPivot.add(elbowServo)

const elbowRing = new THREE.Mesh(new THREE.TorusGeometry(0.033, 0.004, 8, 24), jointAccentMat)
elbowRing.rotation.x = Math.PI / 2
elbowRing.position.y = 0.015
elbowPivot.add(elbowRing)

// Forearm
const forearmPivot = new THREE.Group()
forearmPivot.position.y = 0.05
elbowPivot.add(forearmPivot)

const forearmMesh = makeShadowed(new THREE.Mesh(new THREE.BoxGeometry(0.055, 0.28, 0.055), armMat))
forearmMesh.position.y = 0.14
forearmPivot.add(forearmMesh)

// Forearm strips
const fstripGeo = new THREE.BoxGeometry(0.002, 0.28, 0.057)
const fstripL = new THREE.Mesh(fstripGeo, stripMat)
fstripL.position.set(-0.028, 0.14, 0)
forearmPivot.add(fstripL)
const fstripR = new THREE.Mesh(fstripGeo, stripMat)
fstripR.position.set(0.028, 0.14, 0)
forearmPivot.add(fstripR)

// Wrist
const wrist = makeShadowed(new THREE.Mesh(new THREE.SphereGeometry(0.022, 16, 16), servoMat))
wrist.position.y = 0.28
forearmPivot.add(wrist)

// Gripper base
const gripperBase = makeShadowed(new THREE.Mesh(new THREE.BoxGeometry(0.06, 0.025, 0.035), steelMat))
gripperBase.position.y = 0.305
forearmPivot.add(gripperBase)

// Fingers
const fingerGeo = new THREE.BoxGeometry(0.008, 0.055, 0.025)
const fingerL = makeShadowed(new THREE.Mesh(fingerGeo, gripperMat))
fingerL.position.set(-0.022, 0.34, 0)
forearmPivot.add(fingerL)

const fingerR = makeShadowed(new THREE.Mesh(fingerGeo, gripperMat))
fingerR.position.set(0.022, 0.34, 0)
forearmPivot.add(fingerR)

// Finger tips (accent)
const tipGeo = new THREE.BoxGeometry(0.01, 0.008, 0.027)
const tipL = new THREE.Mesh(tipGeo, jointAccentMat)
tipL.position.set(-0.022, 0.37, 0)
forearmPivot.add(tipL)
const tipR = new THREE.Mesh(tipGeo, jointAccentMat)
tipR.position.set(0.022, 0.37, 0)
forearmPivot.add(tipR)

// ── Wireframe overlay ────────────────────────────────────────────────────────

const wireframeGroup = new THREE.Group()
wireframeGroup.visible = false
robot.add(wireframeGroup)

// We'll rebuild wireframes after first render in animate

// ── Joint axis lines ─────────────────────────────────────────────────────────

const axisVisuals = new THREE.Group()
robot.add(axisVisuals)

function addJointAxis(parent: THREE.Object3D, dir: THREE.Vector3, color: number) {
  const pts = [
    new THREE.Vector3().copy(dir).multiplyScalar(-0.12),
    new THREE.Vector3().copy(dir).multiplyScalar(0.12),
  ]
  const geo = new THREE.BufferGeometry().setFromPoints(pts)
  const mat = new THREE.LineBasicMaterial({ color, transparent: true, opacity: 0.5 })
  const line = new THREE.Line(geo, mat)
  parent.add(line)
  axisVisuals.children // just to reference

  const ring = new THREE.Mesh(
    new THREE.TorusGeometry(0.05, 0.002, 8, 32),
    new THREE.MeshBasicMaterial({ color, transparent: true, opacity: 0.15 })
  )
  if (Math.abs(dir.z) > 0.5) { /* default orientation */ }
  else if (Math.abs(dir.y) > 0.5) ring.rotation.x = Math.PI / 2
  else ring.rotation.z = Math.PI / 2
  parent.add(ring)
}

addJointAxis(shoulderPivot, new THREE.Vector3(0, 0, 1), 0x4a9eff)  // shoulder pan: Z
addJointAxis(upperArmPivot, new THREE.Vector3(0, 1, 0), 0x4ec9b0)  // shoulder lift: Y
addJointAxis(elbowPivot, new THREE.Vector3(0, 1, 0), 0x4ec9b0)     // elbow: Y

// ── CoM marker ───────────────────────────────────────────────────────────────

const comGroup = new THREE.Group()
robot.add(comGroup)

const totalMass = 1.2 + 0.18 + 0.4 + 0.12 + 0.25 + 0.08 + 0.06 + 0.04
const comY = (1.2*0.025 + 0.18*0.08 + 0.4*0.28 + 0.12*0.46 + 0.25*0.55 + 0.08*0.7 + 0.06*0.72 + 0.04*0.75) / totalMass

const comMarker = new THREE.Mesh(new THREE.OctahedronGeometry(0.045), comMat)
comMarker.position.set(0, comY, 0)
comGroup.add(comMarker)

const comLinePts = [new THREE.Vector3(0, comY, 0), new THREE.Vector3(0, 0, 0)]
const comLineGeo = new THREE.BufferGeometry().setFromPoints(comLinePts)
const comLineMat = new THREE.LineDashedMaterial({ color: 0xe5c07b, dashSize: 0.02, gapSize: 0.01, transparent: true, opacity: 0.7 })
const comLine = new THREE.Line(comLineGeo, comLineMat)
comLine.computeLineDistances()
comGroup.add(comLine)

// CoM label ring
const comRingGround = new THREE.Mesh(
  new THREE.RingGeometry(0.035, 0.045, 24),
  new THREE.MeshBasicMaterial({ color: 0xe5c07b, transparent: true, opacity: 0.4, side: THREE.DoubleSide })
)
comRingGround.rotation.x = -Math.PI / 2
comRingGround.position.y = 0.001
comGroup.add(comRingGround)

// ── Viewport controls ────────────────────────────────────────────────────────

const toggleAxesBtn = document.getElementById('toggle-axes') as HTMLButtonElement
const toggleComBtn = document.getElementById('toggle-com') as HTMLButtonElement
const toggleWireBtn = document.getElementById('toggle-wireframe') as HTMLButtonElement
const toggleGridBtn = document.getElementById('toggle-grid') as HTMLButtonElement

let axesVisible = true
let gridVisible = true

toggleAxesBtn.addEventListener('click', () => {
  axesVisible = !axesVisible
  originAxes.visible = axesVisible
  axisVisuals.visible = axesVisible
  toggleAxesBtn.classList.toggle('active', axesVisible)
})

toggleComBtn.addEventListener('click', () => {
  comGroup.visible = !comGroup.visible
  toggleComBtn.classList.toggle('active', comGroup.visible)
})

toggleWireBtn.addEventListener('click', () => {
  wireframeGroup.visible = !wireframeGroup.visible
  toggleWireBtn.classList.toggle('active', wireframeGroup.visible)
})

toggleGridBtn.classList.add('active')
toggleGridBtn.addEventListener('click', () => {
  gridVisible = !gridVisible
  grid.visible = gridVisible
  toggleGridBtn.classList.toggle('active', gridVisible)
})

// ── Sim mode ─────────────────────────────────────────────────────────────────

const simToggle = document.getElementById('sim-toggle') as HTMLButtonElement
const simBar = document.getElementById('sim-bar') as HTMLDivElement
const simPlay = document.getElementById('sim-play') as HTMLButtonElement
const simPause = document.getElementById('sim-pause') as HTMLButtonElement
const simReset = document.getElementById('sim-reset') as HTMLButtonElement
const simProgress = document.getElementById('sim-progress') as HTMLDivElement
const simTimeEl = document.getElementById('sim-time') as HTMLSpanElement
const viewportLabel = document.getElementById('viewport-label') as HTMLSpanElement

let simRunning = false
let simActive = false
let simTime = 0

// Original sim event listeners removed — replaced by persistent-core versions below

function updateSimUI() {
  simPlay.classList.toggle('active', simRunning)
  simPause.classList.toggle('active', !simRunning && simActive)
  simTimeEl.textContent = simTime.toFixed(3) + 's'
  simProgress.style.width = `${Math.min((simTime / 10) * 100, 100)}%`
}

// ── Resize ───────────────────────────────────────────────────────────────────

function resize() {
  const header = document.getElementById('viewport-header')!
  const w = viewportPanel.clientWidth
  const h = viewportPanel.clientHeight - header.offsetHeight - (simActive ? simBar.offsetHeight : 0)
  if (w > 0 && h > 0) {
    renderer.setSize(w, h)
    camera.aspect = w / h
    camera.updateProjectionMatrix()
  }
}
resize()
window.addEventListener('resize', resize)

// ── Animate ──────────────────────────────────────────────────────────────────

let wireframeBuilt = false

function animate() {
  requestAnimationFrame(animate)

  // Build wireframes once
  if (!wireframeBuilt) {
    wireframeBuilt = true
    robot.traverse(child => {
      if (child instanceof THREE.Mesh && child.material !== wireMat && child.geometry) {
        const clone = new THREE.Mesh(child.geometry, wireMat)
        child.getWorldPosition(clone.position)
        child.getWorldQuaternion(clone.quaternion)
        wireframeGroup.add(clone)
      }
    })
  }

  controls.update()

  // CoM diamond gentle spin
  comMarker.rotation.y += 0.01

  // Sim animation
  if (simRunning) {
    simTime += 1 / 60
    updateSimUI()
    const t = simTime

    // Smooth sinusoidal motion across joints
    shoulderPivot.rotation.y = Math.sin(t * 0.8) * 0.6
    upperArmPivot.rotation.x = Math.sin(t * 0.6 + 0.5) * 0.3 - 0.2
    elbowPivot.rotation.x = Math.sin(t * 1.2) * 0.5 + 0.3

    // Gripper open/close cycle
    const grip = Math.sin(t * 2) * 0.5 + 0.5 // 0 to 1
    fingerL.position.x = -0.022 - grip * 0.012
    fingerR.position.x = 0.022 + grip * 0.012
    tipL.position.x = fingerL.position.x
    tipR.position.x = fingerR.position.x
  }

  renderer.render(scene, camera)
}
animate()

// ── Draggable split ──────────────────────────────────────────────────────────

const handle = document.getElementById('resize-handle') as HTMLDivElement
const editorPanel = document.getElementById('editor-panel') as HTMLDivElement
const main = document.getElementById('main') as HTMLDivElement

let dragging = false

handle.addEventListener('mousedown', () => {
  dragging = true
  handle.classList.add('dragging')
  document.body.style.cursor = 'col-resize'
  document.body.style.userSelect = 'none'
})

document.addEventListener('mousemove', (e) => {
  if (!dragging) return
  const rect = main.getBoundingClientRect()
  const pct = ((e.clientX - rect.left) / rect.width) * 100
  editorPanel.style.width = `${Math.min(Math.max(pct, 15), 85)}%`
  resize()
})

document.addEventListener('mouseup', () => {
  if (!dragging) return
  dragging = false
  handle.classList.remove('dragging')
  document.body.style.cursor = ''
  document.body.style.userSelect = ''
})

// ── Kinematic Graph Data Structure ──────────────────────────────────────────

interface KinematicLink {
  name: string
  mass: number
  parent?: string
  children: string[]
}

interface KinematicJoint {
  name: string
  type: string
  axis: string
  parentLink: string
  childLink: string
}

// Define the robot kinematic structure based on SAMPLE_URDF
const kinematicGraph: Record<string, KinematicLink> = {
  'base_link': {
    name: 'base_link',
    mass: 1.2,
    children: ['shoulder_link'],
  },
  'shoulder_link': {
    name: 'shoulder_link',
    mass: 0.18,
    parent: 'base_link',
    children: ['upper_arm'],
  },
  'upper_arm': {
    name: 'upper_arm',
    mass: 0.4,
    parent: 'shoulder_link',
    children: ['elbow_link'],
  },
  'elbow_link': {
    name: 'elbow_link',
    mass: 0.12,
    parent: 'upper_arm',
    children: ['forearm'],
  },
  'forearm': {
    name: 'forearm',
    mass: 0.25,
    parent: 'elbow_link',
    children: ['wrist'],
  },
  'wrist': {
    name: 'wrist',
    mass: 0.08,
    parent: 'forearm',
    children: ['gripper_base'],
  },
  'gripper_base': {
    name: 'gripper_base',
    mass: 0.06,
    parent: 'wrist',
    children: ['finger_left', 'finger_right'],
  },
  'finger_left': {
    name: 'finger_left',
    mass: 0.02,
    parent: 'gripper_base',
    children: [],
  },
  'finger_right': {
    name: 'finger_right',
    mass: 0.02,
    parent: 'gripper_base',
    children: [],
  },
}

const kinematicJoints: Record<string, KinematicJoint> = {
  'shoulder_pan': {
    name: 'shoulder_pan',
    type: 'revolute',
    axis: 'Z',
    parentLink: 'base_link',
    childLink: 'shoulder_link',
  },
  'shoulder_lift': {
    name: 'shoulder_lift',
    type: 'revolute',
    axis: 'Y',
    parentLink: 'shoulder_link',
    childLink: 'upper_arm',
  },
  'elbow': {
    name: 'elbow',
    type: 'revolute',
    axis: 'Y',
    parentLink: 'upper_arm',
    childLink: 'elbow_link',
  },
  'forearm_attach': {
    name: 'forearm_attach',
    type: 'fixed',
    axis: '--',
    parentLink: 'elbow_link',
    childLink: 'forearm',
  },
  'wrist_attach': {
    name: 'wrist_attach',
    type: 'fixed',
    axis: '--',
    parentLink: 'forearm',
    childLink: 'wrist',
  },
  'gripper_attach': {
    name: 'gripper_attach',
    type: 'fixed',
    axis: '--',
    parentLink: 'wrist',
    childLink: 'gripper_base',
  },
  'finger_left_joint': {
    name: 'finger_left_joint',
    type: 'prismatic',
    axis: 'X',
    parentLink: 'gripper_base',
    childLink: 'finger_left',
  },
  'finger_right_joint': {
    name: 'finger_right_joint',
    type: 'prismatic',
    axis: 'X',
    parentLink: 'gripper_base',
    childLink: 'finger_right',
  },
}

// Mapping from link names to Three.js meshes for highlighting
const meshMap: Record<string, THREE.Mesh | THREE.Group> = {
  'base_link': basePlate,
  'shoulder_link': shoulderServo,
  'upper_arm': upperArmMesh,
  'elbow_link': elbowServo,
  'forearm': forearmMesh,
  'wrist': wrist,
  'gripper_base': gripperBase,
  'finger_left': fingerL,
  'finger_right': fingerR,
}

let currentHighlightedMesh: THREE.Mesh | THREE.Group | null = null

function highlightMesh(linkName: string) {
  // Clear previous highlight
  if (currentHighlightedMesh) {
    if (currentHighlightedMesh instanceof THREE.Mesh) {
      const mat = currentHighlightedMesh.material as THREE.MeshStandardMaterial
      if (mat && mat.emissive) mat.emissive.setHex(0x000000)
    }
  }

  // Apply new highlight
  const mesh = meshMap[linkName]
  if (mesh instanceof THREE.Mesh) {
    const mat = mesh.material as THREE.MeshStandardMaterial
    if (mat && mat.emissive) mat.emissive.setHex(0x334400)
    currentHighlightedMesh = mesh
  }
}

function clearHighlight() {
  if (currentHighlightedMesh && currentHighlightedMesh instanceof THREE.Mesh) {
    const mat = currentHighlightedMesh.material as THREE.MeshStandardMaterial
    if (mat && mat.emissive) mat.emissive.setHex(0x000000)
  }
  currentHighlightedMesh = null
}

// ── Build Kinematic Tree UI ──────────────────────────────────────────────────

function buildKinematicTreeUI() {
  const treeContainer = document.getElementById('kinematic-tree')!
  treeContainer.innerHTML = ''

  function buildNode(linkName: string, depth: number = 0) {
    const link = kinematicGraph[linkName]
    if (!link) return

    const nodeEl = document.createElement('div')
    nodeEl.className = 'kt-node link'
    nodeEl.style.paddingLeft = `${10 + depth * 12}px`

    const hasChildren = link.children.length > 0
    const toggleEl = document.createElement('div')
    toggleEl.className = `kt-toggle ${hasChildren ? 'expanded' : ''}`
    if (!hasChildren) toggleEl.style.opacity = '0'

    const labelEl = document.createElement('span')
    labelEl.textContent = `${link.name} (${link.mass} kg)`

    nodeEl.appendChild(toggleEl)
    nodeEl.appendChild(labelEl)

    // Click to highlight in 3D
    labelEl.style.cursor = 'pointer'
    labelEl.addEventListener('click', (e) => {
      e.stopPropagation()
      highlightMesh(linkName)
    })

    // Toggle expand/collapse
    if (hasChildren) {
      toggleEl.style.cursor = 'pointer'
      toggleEl.addEventListener('click', (e) => {
        e.stopPropagation()
        const childrenDiv = nodeEl.nextElementSibling
        if (childrenDiv && childrenDiv.classList.contains('kt-children')) {
          childrenDiv.classList.toggle('visible')
          toggleEl.classList.toggle('expanded')
          toggleEl.classList.toggle('collapsed')
        }
      })
    }

    treeContainer.appendChild(nodeEl)

    // Add joints and children
    if (hasChildren) {
      const childrenDiv = document.createElement('div')
      childrenDiv.className = 'kt-children visible'

      for (const childName of link.children) {
        // Find the joint connecting to this child
        for (const joint of Object.values(kinematicJoints)) {
          if (joint.parentLink === linkName && joint.childLink === childName) {
            const jointEl = document.createElement('div')
            jointEl.className = 'kt-node joint'
            jointEl.style.paddingLeft = `${30 + depth * 12}px`
            jointEl.textContent = `↳ ${joint.name} [${joint.type}, ${joint.axis}]`

            // Show tooltip on hover
            jointEl.addEventListener('mouseenter', () => {
              jointEl.title = `Type: ${joint.type}\nAxis: ${joint.axis}\nParent: ${joint.parentLink}\nChild: ${joint.childLink}`
            })

            childrenDiv.appendChild(jointEl)
            break
          }
        }

        // Recursively add child link
        const tempDiv = document.createElement('div')
        treeContainer.appendChild(tempDiv)
        const oldAppend = treeContainer.appendChild
        treeContainer.appendChild = function (el: any) {
          tempDiv.parentElement!.insertBefore(el, tempDiv.nextSibling)
          return el
        }
        buildNode(childName, depth + 1)
        treeContainer.appendChild = oldAppend
        tempDiv.remove()
      }

      treeContainer.appendChild(childrenDiv)
    }
  }

  buildNode('base_link')
}

buildKinematicTreeUI()

// ── Node Graph Visualization ────────────────────────────────────────────────

let graphCanvasVisible = false
let graphCanvas: HTMLCanvasElement | null = null
let graphCtx: CanvasRenderingContext2D | null = null
let graphContainer: HTMLDivElement | null = null
let graphEventsAttached = false

interface GraphNode {
  linkName: string
  x: number
  y: number
  width: number
  height: number
}

let graphNodes: GraphNode[] = []

function buildNodeGraph() {
  const dpr = window.devicePixelRatio || 1
  const viewWidth = viewportPanel.clientWidth
  const viewHeight = viewportPanel.clientHeight

  // Layout: top-to-bottom tree
  const nodeWidth = 120
  const nodeHeight = 54
  const levelHeight = 110
  const paddingTop = 50
  const paddingBottom = 30

  // Calculate max tree depth first
  let maxDepth = 0
  function calcDepth(linkName: string, depth: number) {
    if (depth > maxDepth) maxDepth = depth
    const link = kinematicGraph[linkName]
    if (link) {
      for (const child of link.children) {
        calcDepth(child, depth + 1)
      }
    }
  }
  calcDepth('base_link', 0)

  const contentHeight = Math.max(viewHeight, paddingTop + (maxDepth + 1) * levelHeight + paddingBottom)

  // Create scrollable container + canvas
  if (!graphContainer) {
    graphContainer = document.createElement('div')
    graphContainer.id = 'kinematic-graph-container'

    // Close button
    const closeBtn = document.createElement('button')
    closeBtn.textContent = '✕'
    closeBtn.title = 'Close graph (G)'
    closeBtn.style.cssText = `
      position: sticky; top: 8px; float: right; margin-right: 12px;
      z-index: 25; background: #333; color: #ccc; border: 1px solid #555;
      border-radius: 4px; width: 28px; height: 28px; cursor: pointer;
      font-size: 14px; line-height: 1; display: flex; align-items: center;
      justify-content: center;
    `
    closeBtn.addEventListener('click', () => {
      graphCanvasVisible = false
      if (graphContainer) graphContainer.style.display = 'none'
      clearHighlight()
      toggleGraphBtn.classList.remove('active')
    })
    graphContainer.appendChild(closeBtn)

    graphCanvas = document.createElement('canvas')
    graphCanvas.id = 'kinematic-graph-canvas'
    graphContainer.appendChild(graphCanvas)
    viewportPanel.appendChild(graphContainer)
    graphCtx = graphCanvas.getContext('2d')!
  }

  // Set canvas size with DPI scaling
  graphCanvas!.width = viewWidth * dpr
  graphCanvas!.height = contentHeight * dpr
  graphCanvas!.style.width = viewWidth + 'px'
  graphCanvas!.style.height = contentHeight + 'px'
  graphCanvas!.style.display = 'block'

  graphCtx = graphCanvas!.getContext('2d')!
  graphCtx.setTransform(dpr, 0, 0, dpr, 0, 0)

  graphNodes = []

  // Count siblings at each depth level
  const levelCounts: Record<number, number> = {}
  function countLevels(linkName: string, depth: number) {
    levelCounts[depth] = (levelCounts[depth] || 0) + 1
    const link = kinematicGraph[linkName]
    if (link) {
      for (const child of link.children) {
        countLevels(child, depth + 1)
      }
    }
  }
  countLevels('base_link', 0)

  const levelIndexes: Record<number, number> = {}

  function layoutNode(linkName: string, depth: number) {
    if (!levelIndexes[depth]) levelIndexes[depth] = 0
    const indexInLevel = levelIndexes[depth]
    const total = levelCounts[depth] || 1

    const xSpacing = Math.max(nodeWidth + 30, viewWidth / (total + 1))
    const xOffset = (viewWidth - total * xSpacing) / 2 + xSpacing / 2
    const x = xOffset + indexInLevel * xSpacing
    const y = paddingTop + depth * levelHeight

    graphNodes.push({
      linkName,
      x: x - nodeWidth / 2,
      y: y - nodeHeight / 2,
      width: nodeWidth,
      height: nodeHeight,
    })

    levelIndexes[depth]++
  }

  // Recursively layout
  function walkLayout(linkName: string, depth: number) {
    layoutNode(linkName, depth)
    const link = kinematicGraph[linkName]
    if (link) {
      for (const child of link.children) {
        walkLayout(child, depth + 1)
      }
    }
  }

  walkLayout('base_link', 0)

  // Render graph
  if (graphCtx) {
    graphCtx.clearRect(0, 0, viewWidth, contentHeight)

    // Draw edges first
    graphCtx.strokeStyle = '#4ec9b0'
    graphCtx.lineWidth = 1.5
    graphCtx.globalAlpha = 0.6

    for (const [linkName, link] of Object.entries(kinematicGraph)) {
      for (const childName of link.children) {
        const parentNode = graphNodes.find((n) => n.linkName === linkName)
        const childNode = graphNodes.find((n) => n.linkName === childName)
        if (parentNode && childNode) {
          graphCtx.beginPath()
          graphCtx.moveTo(parentNode.x + parentNode.width / 2, parentNode.y + parentNode.height)
          graphCtx.lineTo(childNode.x + childNode.width / 2, childNode.y)
          graphCtx.stroke()

          // Draw joint label on edge
          const jx = (parentNode.x + parentNode.width / 2 + childNode.x + childNode.width / 2) / 2
          const jy = (parentNode.y + parentNode.height + childNode.y) / 2

          for (const joint of Object.values(kinematicJoints)) {
            if (joint.parentLink === linkName && joint.childLink === childName) {
              graphCtx.globalAlpha = 1
              graphCtx.fillStyle = '#e5c07b'
              graphCtx.font = '10px monospace'
              graphCtx.textAlign = 'center'
              graphCtx.fillText(joint.type, jx, jy - 2)
              graphCtx.globalAlpha = 0.6
              break
            }
          }
        }
      }
    }

    graphCtx.globalAlpha = 1

    // Draw nodes
    for (const node of graphNodes) {
      const link = kinematicGraph[node.linkName]

      // Node background
      graphCtx.fillStyle = '#1e1e22'
      graphCtx.strokeStyle = '#4ec9b0'
      graphCtx.lineWidth = 2

      // Draw rounded rectangle
      const r = 8
      graphCtx.beginPath()
      graphCtx.moveTo(node.x + r, node.y)
      graphCtx.lineTo(node.x + node.width - r, node.y)
      graphCtx.quadraticCurveTo(node.x + node.width, node.y, node.x + node.width, node.y + r)
      graphCtx.lineTo(node.x + node.width, node.y + node.height - r)
      graphCtx.quadraticCurveTo(node.x + node.width, node.y + node.height, node.x + node.width - r, node.y + node.height)
      graphCtx.lineTo(node.x + r, node.y + node.height)
      graphCtx.quadraticCurveTo(node.x, node.y + node.height, node.x, node.y + node.height - r)
      graphCtx.lineTo(node.x, node.y + r)
      graphCtx.quadraticCurveTo(node.x, node.y, node.x + r, node.y)
      graphCtx.closePath()
      graphCtx.fill()
      graphCtx.stroke()

      // Node text
      graphCtx.fillStyle = '#4ec9b0'
      graphCtx.font = 'bold 12px monospace'
      graphCtx.textAlign = 'center'
      graphCtx.textBaseline = 'top'
      graphCtx.fillText(node.linkName, node.x + node.width / 2, node.y + 8)

      // Mass label
      if (link) {
        graphCtx.fillStyle = '#aaa'
        graphCtx.font = '10px monospace'
        graphCtx.fillText(`${link.mass} kg`, node.x + node.width / 2, node.y + 28)
      }
    }
  }

  // Attach interactive events only once
  if (!graphEventsAttached && graphCanvas) {
    graphCanvas.addEventListener('mousemove', (e) => {
      const rect = graphCanvas!.getBoundingClientRect()
      const mx = e.clientX - rect.left
      const my = e.clientY - rect.top + (graphContainer?.scrollTop || 0)

      for (const node of graphNodes) {
        if (
          mx >= node.x &&
          mx <= node.x + node.width &&
          my >= node.y &&
          my <= node.y + node.height
        ) {
          graphCanvas!.style.cursor = 'pointer'
          highlightMesh(node.linkName)
          return
        }
      }
      graphCanvas!.style.cursor = 'default'
      clearHighlight()
    })

    graphCanvas.addEventListener('click', (e) => {
      const rect = graphCanvas!.getBoundingClientRect()
      const mx = e.clientX - rect.left
      const my = e.clientY - rect.top + (graphContainer?.scrollTop || 0)

      for (const node of graphNodes) {
        if (
          mx >= node.x &&
          mx <= node.x + node.width &&
          my >= node.y &&
          my <= node.y + node.height
        ) {
          highlightMesh(node.linkName)
          break
        }
      }
    })

    graphEventsAttached = true
  }
}

const toggleGraphBtn = document.getElementById('toggle-graph') as HTMLButtonElement

toggleGraphBtn.addEventListener('click', () => {
  graphCanvasVisible = !graphCanvasVisible

  if (graphCanvasVisible) {
    if (!graphContainer) buildNodeGraph()
    else {
      graphContainer.style.display = 'block'
      buildNodeGraph() // rebuild to update layout
    }
  } else {
    if (graphContainer) graphContainer.style.display = 'none'
    clearHighlight()
  }

  toggleGraphBtn.classList.toggle('active', graphCanvasVisible)
})

// Rebuild graph on window resize
window.addEventListener('resize', () => {
  if (graphContainer && graphCanvasVisible) {
    buildNodeGraph()
  }
})

// ── Keyboard shortcuts for viewport toggles ─────────────────────────────────
document.addEventListener('keydown', (e) => {
  // Don't trigger shortcuts when typing in inputs
  const tag = (e.target as HTMLElement).tagName
  if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return

  switch (e.key.toLowerCase()) {
    case 'a':
      toggleAxesBtn.click()
      break
    case 'c':
      toggleComBtn.click()
      break
    case 'w':
      toggleWireBtn.click()
      break
    case 'g':
      if (!e.ctrlKey && !e.metaKey) {
        toggleGridBtn.click()
      }
      break
    case 'n':
      toggleGraphBtn.click()
      break
    case 'escape':
      if (graphCanvasVisible) {
        graphCanvasVisible = false
        if (graphContainer) graphContainer.style.display = 'none'
        clearHighlight()
        toggleGraphBtn.classList.remove('active')
      }
      break
  }
})

// ── Activity bar ─────────────────────────────────────────────────────────────

const panels: Record<string, HTMLElement> = {
  explorer: document.getElementById('panel-explorer')!,
  presets: document.getElementById('panel-presets')!,
  validation: document.getElementById('panel-validation')!,
  kinematic: document.getElementById('panel-kinematic')!,
}

document.querySelectorAll('.ab-btn').forEach(btn => {
  btn.addEventListener('click', () => {
    const panel = (btn as HTMLElement).dataset.panel!
    if (!panel) return
    const wasActive = btn.classList.contains('active')
    document.querySelectorAll('.ab-btn').forEach(b => b.classList.remove('active'))
    Object.values(panels).forEach(p => p.classList.add('hidden'))
    if (!wasActive) {
      btn.classList.add('active')
      if (panels[panel]) panels[panel].classList.remove('hidden')
    }
  })
})

// Collapsible sidebar sections
document.querySelectorAll('.sb-header').forEach(header => {
  header.addEventListener('click', () => {
    const targetId = (header as HTMLElement).dataset.target
    if (!targetId) return
    const list = document.getElementById(targetId)
    if (!list) return
    const arrow = header.querySelector('.arrow')
    const isHidden = list.style.display === 'none'
    list.style.display = isHidden ? '' : 'none'
    if (arrow) arrow.textContent = isHidden ? '\u25BE' : '\u25B8'
  })
})

// Preset click → populate command bar
document.querySelectorAll('.preset-item').forEach(item => {
  item.addEventListener('click', () => {
    const name = (item as HTMLElement).dataset.preset!
    commandInput.value = `add ${name.replace(/-/g, ' ')} to the robot`
    commandInput.focus()
  })
})

// ── Toast notifications ──────────────────────────────────────────────────────

const toastArea = document.getElementById('toast-area') as HTMLDivElement

function showToast(message: string, type: 'success' | 'warning' | 'error' | 'info' = 'info') {
  const toast = document.createElement('div')
  toast.className = `toast ${type}`
  toast.textContent = message
  toastArea.appendChild(toast)
  setTimeout(() => {
    toast.classList.add('fade-out')
    setTimeout(() => toast.remove(), 300)
  }, 3000)
}

// ── Command bar ──────────────────────────────────────────────────────────────

const commandInput = document.getElementById('command-input') as HTMLInputElement
const output = document.getElementById('command-output') as HTMLDivElement
const outputText = document.getElementById('output-text') as HTMLDivElement
const cmdLoading = document.getElementById('cmd-loading') as HTMLDivElement
const acceptBtn = document.querySelector('.action-btn.accept') as HTMLButtonElement
const rejectBtn = document.querySelector('.action-btn.reject') as HTMLButtonElement
const statusText = document.getElementById('status-text') as HTMLSpanElement
const statusDot = document.getElementById('status-dot') as HTMLSpanElement
const statusBadge = document.getElementById('status-badge') as HTMLDivElement

// Command history
const cmdHistory: string[] = []
let historyIdx = -1

// Ctrl+K shortcut
document.addEventListener('keydown', (e) => {
  if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
    e.preventDefault()
    commandInput.focus()
  }
})

const RESPONSES: Record<string, { text: string; stats: string }> = {
  'leg': {
    text: `Added left_leg and right_leg subtrees at base_link.
Hip joints: revolute, ±90°, 50 Nm (matched to torso mass).
Knee joints: revolute, 0–120°, 30 Nm.
Ankle joints: revolute, ±30°, 15 Nm.`,
    stats: '+6 links  +6 joints  +18 params',
  },
  'arm': {
    text: `Extended forearm length from 280mm → 380mm.
Updated inertia tensor for new mass distribution.
Elbow torque limit adjusted: 1.5 Nm → 2.1 Nm.
CoM shifted +28mm — still within support polygon.`,
    stats: '0 links  0 joints  +4 params modified',
  },
  'camera': {
    text: `Added depth_camera link at wrist (RealSense D435 preset).
Fixed joint, facing forward, 10° downward tilt.
FOV: 87° × 58°, range: 0.1–10m.
Added <sensor> element with plugin reference.`,
    stats: '+1 link  +1 joint  +1 sensor',
  },
  'gripper': {
    text: `Replaced current parallel jaw with 3-finger adaptive gripper.
Robotiq-style design, 60N grip force, 120mm max opening.
Added 6 joints (2 per finger) with coupled motion.`,
    stats: '+6 links  +6 joints  replaced 2 existing',
  },
  'mirror': {
    text: `Mirrored right_arm subtree → left_arm.
All joint axes reflected across YZ plane.
Preserved torque limits and inertia tensors.
Auto-generated collision avoidance constraints.`,
    stats: '+5 links  +4 joints  created',
  },
  'stiffen': {
    text: `Increased joint damping coefficients:
shoulder_pan: 0.5 → 2.0 Nm·s/rad
shoulder_lift: 0.7 → 2.5 Nm·s/rad
elbow: 0.3 → 1.5 Nm·s/rad
This should reduce oscillation in sim.`,
    stats: '3 joints modified',
  },
  'quadruped': {
    text: `Generated quadruped base structure (MIT Mini Cheetah-style).
12-DOF: 3 joints per leg (hip, thigh, knee).
Total mass: 9.2 kg. Standing height: 350mm.
Actuators: T-Motor AK80-9 (18 Nm) on all joints.`,
    stats: '+13 links  +12 joints  new robot',
  },
}

function getResponse(cmd: string): { text: string; stats: string } {
  const lower = cmd.toLowerCase()
  for (const [key, resp] of Object.entries(RESPONSES)) {
    if (lower.includes(key)) return resp
  }
  return {
    text: `Analyzed: "${cmd}"
Computed kinematic graph diff.
2 nodes modified, 0 added, 0 removed.
All validation checks passed.`,
    stats: '2 params modified',
  }
}

function typeText(text: string, el: HTMLDivElement, cb?: () => void) {
  el.textContent = ''
  el.classList.add('typing-cursor')
  let i = 0
  const interval = setInterval(() => {
    el.textContent += text[i]
    i++
    if (i >= text.length) {
      clearInterval(interval)
      el.classList.remove('typing-cursor')
      if (cb) cb()
    }
  }, 8)
}

function setStatus(text: string, color: string) {
  statusText.textContent = text
  statusDot.style.background = color
  statusBadge.style.color = color
  statusBadge.style.borderColor = color + '33'
  statusBadge.style.background = color + '15'
}

commandInput.addEventListener('keydown', (e) => {
  // History navigation
  if (e.key === 'ArrowUp' && cmdHistory.length > 0) {
    e.preventDefault()
    if (historyIdx < cmdHistory.length - 1) historyIdx++
    commandInput.value = cmdHistory[cmdHistory.length - 1 - historyIdx]
    return
  }
  if (e.key === 'ArrowDown') {
    e.preventDefault()
    if (historyIdx > 0) { historyIdx--; commandInput.value = cmdHistory[cmdHistory.length - 1 - historyIdx] }
    else { historyIdx = -1; commandInput.value = '' }
    return
  }

  if (e.key !== 'Enter') return
  const cmd = commandInput.value.trim()
  if (!cmd) return

  cmdHistory.push(cmd)
  historyIdx = -1
  commandInput.value = ''

  setStatus('thinking...', '#e5c07b')
  output.classList.add('hidden')
  cmdLoading.classList.remove('hidden')

  const delay = 600 + Math.random() * 800
  setTimeout(() => {
    cmdLoading.classList.add('hidden')
    const resp = getResponse(cmd)
    output.classList.remove('hidden')

    typeText(`↳ ${resp.text}\n\n  ${resp.stats}`, outputText, () => {
      setStatus('ready', '#4ec9b0')
    })
  }, delay)
})

acceptBtn.addEventListener('click', () => {
  outputText.textContent = '✓ Changes applied to robot.urdf'
  outputText.style.color = '#4ec9b0'
  showToast('Changes applied successfully', 'success')
  setTimeout(() => { output.classList.add('hidden'); outputText.style.color = '' }, 1200)
})

rejectBtn.addEventListener('click', () => {
  outputText.textContent = '✗ Changes discarded.'
  outputText.style.color = '#f44336'
  showToast('Changes discarded', 'warning')
  setTimeout(() => { output.classList.add('hidden'); outputText.style.color = '' }, 800)
})

// ── Init toast ───────────────────────────────────────────────────────────────
setTimeout(() => showToast('Loaded robot.urdf — 9 links, 7 joints', 'success'), 500)
setTimeout(() => showToast('Validation: 5 passed, 1 warning (CoM near edge)', 'warning'), 1200)

// ── Simulation Mode Integration ──────────────────────────────────────────────
import { invoke } from '@tauri-apps/api/core'

// Simulation state
let simCoreRunning = false
let simStepIntervalId: number | null = null

// Joint state display
const simStateDisplay = document.createElement('div')
simStateDisplay.id = 'sim-state-display'
simStateDisplay.className = 'sim-state-display'
simStateDisplay.style.cssText = `
  position: absolute;
  top: 48px;
  right: 12px;
  background: rgba(28, 28, 36, 0.95);
  border: 1px solid #4ec9b0;
  border-radius: 8px;
  padding: 12px;
  font-family: monospace;
  font-size: 11px;
  color: #e0e0e0;
  max-width: 240px;
  max-height: 300px;
  overflow-y: auto;
  z-index: 100;
  display: none;
  backdrop-filter: blur(8px);
`
viewportPanel.appendChild(simStateDisplay)

async function initializeSimulation() {
  try {
    console.log('[Sim] Initializing simulation core...')
    await invoke('start_core')
    simCoreRunning = true
    console.log('[Sim] Core started successfully')

    console.log('[Sim] Loading robot model...')
    await invoke('sim_load', { path: 'core/test_data/simple_arm.urdf' })
    console.log('[Sim] Robot model loaded')

    console.log('[Sim] Getting initial state...')
    const initialState = await invoke('sim_get_state')
    console.log('[Sim] Initial state:', initialState)

    // Show state display
    simStateDisplay.style.display = 'block'
    updateSimStateDisplay(initialState)
  } catch (error) {
    console.error('[Sim] Error initializing simulation:', error)
    showToast(`Simulation error: ${String(error)}`, 'error')
    simCoreRunning = false
  }
}

async function shutdownSimulation() {
  try {
    if (simStepIntervalId !== null) {
      clearInterval(simStepIntervalId)
      simStepIntervalId = null
    }
    await invoke('stop_core')
    simCoreRunning = false
    simStateDisplay.style.display = 'none'
    console.log('[Sim] Core stopped')
  } catch (error) {
    console.error('[Sim] Error stopping simulation:', error)
    showToast(`Error stopping simulation: ${String(error)}`, 'error')
  }
}

async function stepSimulation() {
  if (!simCoreRunning) return
  try {
    await invoke('sim_step', { n_steps: 1 })
    const state = await invoke('sim_get_state')
    updateSimStateDisplay(state)
    updateRobotFromSimState(state)
  } catch (error) {
    console.error('[Sim] Error stepping simulation:', error)
  }
}

function updateSimStateDisplay(state: any) {
  try {
    let html = '<div style="font-weight: bold; color: #4ec9b0; margin-bottom: 8px;">Simulation State</div>'

    if (state && typeof state === 'object') {
      // Display time
      if (state.time !== undefined) {
        html += `<div><span style="color: #e5c07b;">time:</span> ${(state.time as number).toFixed(3)}s</div>`
      }

      // Display joint states
      if (state.joints && typeof state.joints === 'object') {
        html += '<div style="margin-top: 6px; color: #999;">Joints:</div>'
        for (const [name, joint] of Object.entries(state.joints)) {
          if (typeof joint === 'object' && joint !== null) {
            const j = joint as any
            const pos = j.position?.toFixed(3) || '0.000'
            const vel = j.velocity?.toFixed(3) || '0.000'
            html += `<div style="margin-left: 8px;">
              <span style="color: #99ccff;">${name}</span>
              <div style="margin-left: 8px; color: #999; font-size: 10px;">
                pos: ${pos} | vel: ${vel}
              </div>
            </div>`
          }
        }
      }

      // Display contact info
      if (state.contacts !== undefined) {
        html += `<div style="margin-top: 6px; color: #999;">Contacts: <span style="color: #f44336;">${state.contacts}</span></div>`
      }

      // Display energy
      if (state.energy !== undefined) {
        html += `<div style="margin-top: 6px; color: #999;">Energy: <span style="color: #4ec9b0;">${(state.energy as number).toFixed(3)}J</span></div>`
      }
    }

    simStateDisplay.innerHTML = html
  } catch (e) {
    console.error('[Sim] Error updating display:', e)
  }
}

function updateRobotFromSimState(state: any) {
  try {
    if (!state || !state.joints) return

    const joints = state.joints as any

    // Update shoulder pan (Z rotation)
    if (joints.shoulder_pan?.position !== undefined) {
      shoulderPivot.rotation.y = joints.shoulder_pan.position
    }

    // Update shoulder lift (X rotation)
    if (joints.shoulder_lift?.position !== undefined) {
      upperArmPivot.rotation.x = joints.shoulder_lift.position
    }

    // Update elbow (X rotation)
    if (joints.elbow?.position !== undefined) {
      elbowPivot.rotation.x = joints.elbow.position
    }

    // Update gripper fingers
    if (joints.finger_left_joint?.position !== undefined) {
      fingerL.position.x = -0.022 + joints.finger_left_joint.position
      tipL.position.x = fingerL.position.x
    }

    if (joints.finger_right_joint?.position !== undefined) {
      fingerR.position.x = 0.022 + joints.finger_right_joint.position
      tipR.position.x = fingerR.position.x
    }
  } catch (e) {
    console.error('[Sim] Error updating robot from state:', e)
  }
}

// Update sim mode toggle to use persistent core
simToggle.addEventListener('click', async () => {
  simActive = !simActive
  simBar.classList.toggle('hidden', !simActive)
  simToggle.classList.toggle('running', simActive)
  simToggle.querySelector('span')!.textContent = simActive ? 'Exit Sim' : 'Simulate'
  viewportLabel.textContent = simActive ? 'Simulation — MuJoCo' : '3D Preview'

  if (simActive) {
    // Enter simulation mode
    try {
      await initializeSimulation()
      showToast('Entered simulation mode (MuJoCo)', 'success')
    } catch (error) {
      console.error('[Sim] Failed to initialize:', error)
      simActive = false
      simToggle.classList.remove('running')
      simBar.classList.add('hidden')
      showToast('Failed to initialize simulation', 'error')
    }
  } else {
    // Exit simulation mode
    simRunning = false
    simTime = 0
    await shutdownSimulation()

    // Reset pose
    shoulderPivot.rotation.y = 0
    upperArmPivot.rotation.x = 0
    elbowPivot.rotation.x = 0
    fingerL.position.x = -0.022
    fingerR.position.x = 0.022
    updateSimUI()
    showToast('Exited simulation mode', 'info')
  }
  resize()
})

// Update play/pause to use persistent stepping
simPlay.addEventListener('click', () => {
  if (!simCoreRunning) return
  simRunning = true
  if (simStepIntervalId !== null) {
    clearInterval(simStepIntervalId)
  }
  // Step at ~60 Hz
  simStepIntervalId = setInterval(async () => {
    await stepSimulation()
  }, 1000 / 60) as unknown as number
  updateSimUI()
})

simPause.addEventListener('click', () => {
  simRunning = false
  if (simStepIntervalId !== null) {
    clearInterval(simStepIntervalId)
    simStepIntervalId = null
  }
  updateSimUI()
})

simReset.addEventListener('click', async () => {
  if (!simCoreRunning) return
  simRunning = false
  if (simStepIntervalId !== null) {
    clearInterval(simStepIntervalId)
    simStepIntervalId = null
  }
  try {
    await invoke('sim_reset')
    const state = await invoke('sim_get_state')
    updateRobotFromSimState(state)
    simTime = 0
    updateSimUI()
  } catch (error) {
    console.error('[Sim] Reset error:', error)
  }
})

// Optional: Test core integration on page load
async function testCoreIntegration() {
  try {
    console.log('[Test] Core integration available (invoke function loaded)')
  } catch (error) {
    console.warn('[Test] Tauri invoke not available in this context')
  }
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => {
    setTimeout(testCoreIntegration, 500)
  })
} else {
  setTimeout(testCoreIntegration, 500)
}
